const $ = id => document.getElementById(id);
const num = v => Number(v) || 0;
const money = v => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(num(v));
const today = () => new Date().toISOString().slice(0, 10);
const addDays = (dateStr, days) => {
  const d = new Date(dateStr || today());
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

const els = {
  orderType: $('orderType'), shippingMode: $('shippingMode'), readySendBtn: $('readySendBtn'),
  demoBtn: $('demoBtn'), saveQuoteBtn: $('saveQuoteBtn'), copySummaryBtn: $('copySummaryBtn'), customerPdfBtn: $('customerPdfBtn'), printBtn: $('printBtn'), resetBtn: $('resetBtn'),
  quoteNumber: $('quoteNumber'), quoteDate: $('quoteDate'), validThrough: $('validThrough'), turnaround: $('turnaround'), quoteTitle: $('quoteTitle'), customerName: $('customerName'), qty: $('qty'), unitsPerItem: $('unitsPerItem'), presetSelect: $('presetSelect'), depositPercent: $('depositPercent'), quoteStatus: $('quoteStatus'), quoteNotes: $('quoteNotes'), customerNotes: $('customerNotes'), assumptions: $('assumptions'),
  filamentCount: $('filamentCount'), spoolWeight: $('spoolWeight'), filament1Cost: $('filament1Cost'), filament1Used: $('filament1Used'), filament2Cost: $('filament2Cost'), filament2Used: $('filament2Used'), filament3Cost: $('filament3Cost'), filament3Used: $('filament3Used'), filament4Cost: $('filament4Cost'), filament4Used: $('filament4Used'), simplePackaging: $('simplePackaging'), simpleShipping: $('simpleShipping'), simpleHardware: $('simpleHardware'), designHours: $('designHours'), designRate: $('designRate'), postHours: $('postHours'), postRate: $('postRate'), machineHours: $('machineHours'), machineRate: $('machineRate'), marketplacePercent: $('marketplacePercent'), simpleSummary: $('simpleSummary'), generateQuoteBtn: $('generateQuoteBtn'),
  advancedToggle: $('advancedToggle'), advancedToggleText: $('advancedToggleText'), advancedPanel: $('advancedPanel'), directItems: $('directItems'), overheadItems: $('overheadItems'), addDirectBtn: $('addDirectBtn'), addOverheadBtn: $('addOverheadBtn'), applyHelpersBtn: $('applyHelpersBtn'), tpl: $('lineItemTemplate'),
  batchName: $('batchName'), batchSku: $('batchSku'), batchUnits: $('batchUnits'), batchColors: $('batchColors'), batchRollWeight: $('batchRollWeight'), batchPriceTarget: $('batchPriceTarget'), batchFilament1Cost: $('batchFilament1Cost'), batchFilament1Used: $('batchFilament1Used'), batchFilament2Cost: $('batchFilament2Cost'), batchFilament2Used: $('batchFilament2Used'), batchFilament3Cost: $('batchFilament3Cost'), batchFilament3Used: $('batchFilament3Used'), batchFilament4Cost: $('batchFilament4Cost'), batchFilament4Used: $('batchFilament4Used'), batchPackaging: $('batchPackaging'), batchLabor: $('batchLabor'), batchOther: $('batchOther'), batchOverhead: $('batchOverhead'), batchSold: $('batchSold'), batchLocation: $('batchLocation'), applyBatchBtn: $('applyBatchBtn'),
  profitMode: $('profitMode'), suggestedMode: $('suggestedMode'), profitValue: $('profitValue'), discount: $('discount'), taxPreset: $('taxPreset'), salesTax: $('salesTax'), roundingMode: $('roundingMode'),
  sumPerItem: $('sumPerItem'), sumMargin: $('sumMargin'), sumBreakEven: $('sumBreakEven'), profitGuardrail: $('profitGuardrail'), quoteConfidence: $('quoteConfidence'), sumDirect: $('sumDirect'), sumOverhead: $('sumOverhead'), sumProfit: $('sumProfit'), sumDeposit: $('sumDeposit'), sumBalance: $('sumBalance'), sumQuote: $('sumQuote'),
  outDirect: $('outDirect'), outOverhead: $('outOverhead'), outBase: $('outBase'), outProfit: $('outProfit'), outPerItem: $('outPerItem'), outBreakEven: $('outBreakEven'), outMargin: $('outMargin'), outPreDiscount: $('outPreDiscount'), outDiscount: $('outDiscount'), outBeforeTax: $('outBeforeTax'), outRoundedBeforeTax: $('outRoundedBeforeTax'), outRoundingGain: $('outRoundingGain'), outTax: $('outTax'), outDeposit: $('outDeposit'), outBalance: $('outBalance'), outFinal: $('outFinal'),
  quoteSummary: $('quoteSummary'), profitWarning: $('profitWarning'), financeReadyView: $('financeReadyView'), copyFinanceBtn: $('copyFinanceBtn'), customerQuoteView: $('customerQuoteView'),
  batchUnitCost: $('batchUnitCost'), batchTotalCost: $('batchTotalCost'), batchUnitsOut: $('batchUnitsOut'), batchUnsoldValue: $('batchUnsoldValue'), materialUnitCost: $('materialUnitCost'), activePreset: $('activePreset'), batchSummary: $('batchSummary'), inventoryReadyView: $('inventoryReadyView'),
  savedQuotesSelect: $('savedQuotesSelect'), loadQuoteBtn: $('loadQuoteBtn'), deleteQuoteBtn: $('deleteQuoteBtn'), historySummary: $('historySummary'),
  pdfTitle: $('pdfTitle'), pdfSubtitle: $('pdfSubtitle'), pdfQuoteNumber: $('pdfQuoteNumber'), pdfQuoteDate: $('pdfQuoteDate'), pdfValidThrough: $('pdfValidThrough'), pdfTurnaround: $('pdfTurnaround'), pdfStatus: $('pdfStatus'), pdfCustomerName: $('pdfCustomerName'), pdfQty: $('pdfQty'), pdfPerItem: $('pdfPerItem'), pdfProject: $('pdfProject'), pdfSubtotal: $('pdfSubtotal'), pdfTax: $('pdf
