const assert=require('node:assert/strict');
const fs=require('node:fs');
const read=file=>fs.readFileSync(require.resolve(`../${file}`),'utf8');
const ui=read('js/job-assets-ui.js'),model=read('js/job-asset-model.js'),css=read('css/job-assets.css');
const migration=read('supabase/migrations/202607280001_authoritative_asset_lifecycle.sql');
for(const page of ['quote.html','orders-admin.html','production-control.html','product-recipes.html','customer-360.html'])assert.match(read(page),/data-job-assets/);
assert.match(ui,/asset_links!inner/,'entity context filters at metadata query boundary');
assert.match(ui,/x-upsert':'false/,'storage never overwrites an existing revision');
assert.match(ui,/expiresIn:SIGNED_SECONDS/);assert.match(ui,/SIGNED_SECONDS=300/);
assert.match(ui,/if\(pending\)return/,'double click is guarded');
assert.match(ui,/objectCreated&&!metadataCreated/);assert.match(ui,/removeExact\(path\)/,'only exact operation object is cleanup eligible');
assert.match(ui,/Uploaded but link failed/);assert.match(ui,/cleanup required/i);
assert.doesNotMatch(ui,/localStorage|service_role|createPublicUrl/);
assert.doesNotMatch(ui,/console\.(log|error)/,'private asset details are not logged');
assert.match(model,/manifestState/);assert.match(model,/currentVersions/);assert.match(model,/status==='archived'/);
assert.match(migration,/source\.record_key=v_quote\.id::text/,'handoff uses Quote database ID');
assert.match(migration,/'order',new\.id::text/,'handoff uses Order database ID');
assert.match(migration,/on conflict\(asset_revision_id,record_type,record_key\) do nothing/,'handoff is idempotent');
assert.match(migration,/asset\.designation='customer_supplied'/,'only safely-defined designation transfers');
assert.match(migration,/source\.owner_id=new\.user_id/);assert.match(migration,/asset\.owner_id=new\.user_id/);
assert.doesNotMatch(migration,/storage\.objects|delete from public\.asset/,'migration does not destroy records or bytes');
assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/min-height:44px/);assert.match(css,/1180px/);
for(const page of ['index.html','collections.html','custom-3d-printing-aurora-ohio.html'])assert.doesNotMatch(read(page),/data-job-assets|job-assets-ui/,'public RC5 remains isolated');
console.log('RC2.3 authoritative asset lifecycle assertions passed');
