const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const vm=require('node:vm');
const read=file=>fs.readFileSync(file,'utf8');
const page=read('fundraiser.html');
const js=read('js/fundraiser-intake.js');
const css=read('assets/css/fundraiser-intake.css');
const migration=read('supabase/migrations/202607280004_generic_campaign_intake.sql');
const manager=read('campaign-manager.html');
const rc24=read('supabase/migrations/202607280002_campaign_submission_authority.sql');
const rc25=read('supabase/migrations/202607280003_campaign_order_conversion.sql');
const docs=read('ENGINE_RC2_7_GENERIC_CAMPAIGN_INTAKE.md');

assert.equal(fs.existsSync('fundraiser.html'),true,'existing public URL is preserved');
assert.match(js,/get_public_campaign/,'campaign loads through existing public authority');
assert.match(js,/campaign\.status!==['"]active['"]/,'inactive/scheduled/closed campaigns cannot submit');
assert.match(js,/Campaign closed/,'closed campaign state exists');
assert.match(js,/state\.lines=new Map|lines:new Map/,'multiple distinct product lines are modeled');
assert.match(js,/personalization_requested:line\.personalized/,'standard and personalized items share one submission');
assert.match(js,/Number\.isInteger/,'quantity must be an integer');
assert.match(js,/personalization_limits\?\.required/,'required personalization is checked');
assert.match(migration,/Personalization is unavailable/g,'server rejects unauthorized personalization');
assert.match(migration,/p\.campaign_id=v_campaign\.id and p\.enabled=true/,'server checks product/campaign relationship');
assert.doesNotMatch(js,/\b(?:total|subtotal|price)\s*:/i,'browser sends no authoritative price or total');
assert.match(js,/submit_campaign_submission/,'browser maps to RC2.4 submission RPC');
assert.match(js,/result\.submission_reference/,'server result is authoritative');
assert.match(js,/crypto\?\.randomUUID|crypto\.getRandomValues/,'attempt UUID is cryptographically generated');
assert.match(js,/sessionStorage\.getItem\(STORAGE_KEY\)/,'timeout/refresh retry preserves the key');
assert.match(js,/if\(state\.inFlight\)return/,'double-click is locked');
assert.match(js,/conflicting_replay/,'conflicting replay has a safe state');
assert.match(page,/confirmation-reference/,'safe public reference has a confirmation target');
assert.match(page,/not yet an OliPoly Order/i,'confirmation states not yet an Order');
assert.match(page,/Payment is not verified|instructional/i,'payment selection is not evidence');
assert.doesNotMatch(js,/location\.(?:assign|replace)|window\.location\s*=/,'no automatic redirect occurs');
for(const forbidden of ['orders','production_jobs','inventory_transactions','financial_entries','invoices'])assert.doesNotMatch(migration,new RegExp(`insert into public\\.${forbidden}`,'i'),`intake does not create ${forbidden}`);
assert.doesNotMatch(js+migration,/(send_email|mailto:)/i,'intake sends no automatic email');
for(const table of ['campaign_submissions','campaign_submission_items'])assert.match(rc24,new RegExp(`revoke all on table public\\.${table} from public, anon, authenticated`,'i'),'anonymous staging reads remain denied');
assert.match(rc24,/revoke all on function public\.review_campaign_submission\(uuid,text,text\) from public, anon/i,'public review remains denied');
assert.match(rc25,/revoke all on function public\.convert_campaign_submission_to_order\(uuid\) from public, anon/i,'public conversion remains denied');
assert.match(js,/\.textContent=/,'customer-facing dynamic text uses safe text nodes');
assert.doesNotMatch(js,/console\.(?:log|debug|info|warn|error)/,'PII is not logged');
assert.doesNotMatch(js,/service_role|service-role/i,'public JS has no service-role credential');
assert.match(migration,/octet_length\(p_request::text\)>65536/,'payload is limited');
assert.match(migration,/jsonb_array_length\(p_request->'items'\) not between 1 and 25/,'item count is limited');
assert.match(manager,/Generic public campaign intake/,'existing manager queue identifies generic intake');
assert.match(manager,/Not yet an Order/,'manager retains staging language');
assert.match(manager,/review_status==='approved_for_conversion'/,'RC2.5 conversion remains review gated');
assert.match(manager,/payment_evidence_state/,'manager shows unverified evidence');
assert.equal(crypto.createHash('sha256').update(read('niles.html')).digest('hex'),'e09e36606edb816d5d1e2f09c1390f7c1f517ccf5af2f788adbb2f3f0973a279','Niles remains byte-for-byte unchanged from RC2.7 baseline');
assert.match(docs,/Automatic Tally ingestion remains inactive/i,'Tally boundary is documented');
assert.match(css,/min-height:44px/,'touch controls meet 44px target');
assert.match(css,/@media\(max-width:600px\)/,'mobile stacking is isolated');
assert.doesNotMatch(page,/style=/,'RC5 visual behavior is isolated in the intake stylesheet');
const ids=[...page.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length,'page contains no duplicate IDs');
for(const ref of [...page.matchAll(/(?:src|href)="((?!https?:|#)[^"]+)"/g)].map(match=>match[1]))assert.equal(fs.existsSync(ref),true,`local reference exists: ${ref}`);
assert.doesNotMatch(page+js+css+migration,/^(?:<{7}|={7}|>{7})/m,'no conflict artifacts exist');
assert.match(migration,/reject_campaign_submission_snapshot_mutation|create or replace function public\.submit_campaign_submission/,'RC2.4 authority is extended, not competed with');
assert.match(migration,/security definer set search_path = public, pg_temp/g,'public functions keep fixed search paths');
assert.match(migration,/revoke all on function public\.submit_campaign_submission\(jsonb\) from public/,'writer grants are explicit');

const sandbox={module:{exports:{}},exports:{},globalThis:{crypto:crypto.webcrypto},crypto:crypto.webcrypto};
vm.runInNewContext(js,sandbox);
assert.match(sandbox.module.exports.uuid(),/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,'attempt key is a UUID');
assert.equal(sandbox.module.exports.SOURCE,'generic_public_campaign');
assert.equal(sandbox.module.exports.MAX_ITEMS,25);
console.log('RC2.7 generic campaign intake structural assertions passed');
