const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const migration=fs.readFileSync('supabase/migrations/202607280003_campaign_order_conversion.sql','utf8');
const manager=fs.readFileSync('campaign-manager.html','utf8');
const managerJs=fs.readFileSync('js/campaign-manager.js','utf8');
const orders=fs.readFileSync('orders-admin.html','utf8');
const customer=fs.readFileSync('js/customer-360.js','utf8');
const doc=fs.readFileSync('ENGINE_RC2_5_CAMPAIGN_ORDER_CONVERSION.md','utf8');
const has=(pattern,message)=>assert.match(migration,pattern,message);

has(/create sequence if not exists public\.olipoly_order_number_seq[\s\S]*no cycle/i,'global noncycling sequence exists');
has(/max\(substring\(order_number from '\^OP-\(\[0-9\]\{6,\}\)\$'\)::bigint\)[\s\S]*where order_number ~ '\^OP-\[0-9\]\{6,\}\$'/,'migration initialization ignores malformed history');
has(/setval\([\s\S]*coalesce\([\s\S]*\+ 1,[\s\S]*false/,'first nextval is above conforming history');
has(/allocate_order_number\(\)[\s\S]*nextval\('public\.olipoly_order_number_seq'/,'runtime allocation uses nextval');
assert.doesNotMatch(migration,/max\([^;]+allocate_order_number/,'allocator does not scan maxima');
has(/revoke all on function public\.allocate_order_number\(\) from public, anon, authenticated/,'allocator is not browser callable');
has(/orders_order_number_unique_idx on public\.orders\(order_number\)/,'Order number is unique');
has(/respond_to_quote_public[\s\S]*v_order_number := public\.allocate_order_number\(\)/,'future Quotes use allocator');
assert.doesNotMatch(migration,/regexp_replace\(v_quote\.quote_number, '\^Q-', 'OP-'/,'Quote suffix no longer allocates Orders');
has(/if coalesce\(v_quote\.customer_response,''\) = 'accepted'[\s\S]*return jsonb_build_object\('response','accepted'/,'Quote retries return existing evidence before allocation');
has(/campaign_submission_id uuid references public\.campaign_submissions[\s\S]*orders_one_per_campaign_submission_idx/,'one Order per submission');
has(/convert_campaign_submission_to_order[\s\S]*auth\.uid\(\)[\s\S]*for update/,'conversion authenticates and locks');
has(/review_status <> 'approved_for_conversion'/,'only approved submissions convert');
has(/sum\(i\.authoritative_line_subtotal\)[\s\S]*accepted_total is distinct from v_expected/,'stored lines and totals are validated');
assert.doesNotMatch(migration,/convert_campaign_submission_to_order[\s\S]*from public\.campaign_products/,'conversion never reprices current products');
has(/jsonb_agg\(jsonb_build_object\([\s\S]*personalization_selection[\s\S]*order by i\.line_sequence/,'ordered line and personalization snapshots persist');
has(/v_submission\.accepted_total,0,v_submission\.accepted_total,'unpaid'/,'explicit zero deposit, full balance, unpaid');
has(/'unresolved_review_required',null,v_snapshot/,'customer remains unresolved without trusted RC2.4 identity');
assert.doesNotMatch(migration,/customer_snapshot->>'(?:name|email)'[\s\S]*(?:join|from public\.customers)/,'no approximate customer lookup');
has(/campaign_order_conversion_snapshots[\s\S]*before update or delete/,'accepted conversion snapshot is immutable');
has(/converted_order_id is not null[\s\S]*review_status='converted'/,'converted state requires exact Order evidence');
has(/revoke all on function public\.convert_campaign_submission_to_order\(uuid\) from public, anon/,'anonymous conversion denied');
has(/grant execute on function public\.convert_campaign_submission_to_order\(uuid\) to authenticated/,'authenticated conversion is narrowly granted');
has(/set search_path = public, pg_temp/,'fixed function search paths exist');
has(/create_production_job_for_order[\s\S]*if found then return jsonb_build_object\('outcome','already_linked'/,'manual production handoff is idempotent');
assert.doesNotMatch(migration,/convert_campaign_submission_to_order[\s\S]*perform public\.create_production_job_for_order/,'conversion does not invoke Production handoff');
assert.doesNotMatch(migration,/insert into public\.(financial_entries|inventory_transactions)/,'conversion migration posts no Finance or Inventory record');
assert.doesNotMatch(migration,/(send_email|mailto:|square|niles)/i,'migration sends no email and does not touch Niles/payment links');
assert.match(managerJs,/convertSubmission:[\s\S]*rpc\/convert_campaign_submission_to_order/,'manager calls one atomic RPC');
assert.match(manager,/review_status==='approved_for_conversion'[\s\S]*data-convert/,'conversion UI is approval gated');
assert.match(manager,/conversionInFlight\.has\(id\)[\s\S]*conversionInFlight\.add\(id\)/,'duplicate click lock exists');
assert.match(manager,/confirm\(`[\s\S]*does not record payment, start Production, send email/,'deliberate confirmation states side effects');
assert.match(manager,/orders-admin\.html\?order=/,'converted result links to Orders Admin');
assert.match(orders,/Source: Campaign[\s\S]*Immutable submitted items[\s\S]*personalization_selection/,'Orders displays source/items/personalization');
assert.match(customer,/campaign_customer_link_status !== 'linked'[\s\S]*x\.id && y\.id/,'Customer 360 isolates unresolved campaign identity');
assert.match(customer,/Campaign \$\{o\.campaign_code[\s\S]*campaign_public_reference/,'Customer timeline presents safe campaign attribution');
assert.match(doc,/RC2\.6 boundary/i,'Niles remains future work');
assert.doesNotMatch(migration,/alter table public\.orders[\s\S]*update public\.orders set order_number/i,'historical Orders are not renumbered');
assert.doesNotMatch(migration,/invoice_number\s*:=|update public\.orders set invoice_number/,'invoice allocation remains unchanged');
assert.match(manager,/min-height:44px/,'touch target contract remains');
assert.match(manager,/@media\(max-width:850px\)/,'mobile layout remains');

const sandbox={globalThis:{},module:{exports:{}},exports:{},console};
vm.runInNewContext(managerJs,sandbox);
assert.equal(typeof sandbox.module.exports.api.convertSubmission,'function','changed manager JavaScript parses and exports conversion API');
console.log('RC2.5 campaign Order conversion authority assertions passed');
