const assert=require('node:assert/strict'); const fs=require('node:fs');
const js=fs.readFileSync('finance-pro.js','utf8'); const html=fs.readFileSync('finance-pro.html','utf8'); const sql=fs.readFileSync('supabase/migrations/202608010004_full_finance_correction_authority.sql','utf8'); const matrix=fs.readFileSync('FINANCE_CORRECTION_FIELD_MATRIX.md','utf8');
assert.match(js,/effectiveEntryFor\(entry\)[\s\S]*effective_version_at/,'correction starts from the authoritative server-resolved effective entry');
assert.match(js,/setOriginalFieldsReadOnly\(false\)/,'full business form is editable');
assert.doesNotMatch(js,/\['entryAmount','shippingCharged','salesTaxCollected'[\s\S]*value = '0\.00'/,'correction no longer clears full financial form');
assert.match(html,/correctionDestinationCounty[\s\S]*correctionSalesTaxRate[\s\S]*correctionTaxOverrideEnabled[\s\S]*correctionTaxOverrideReason[\s\S]*correctionReview/,'county, rate, override, explanation and review are exposed');
assert.match(html,/correctionCalculatedTax" type="number" readonly/,'tax is calculated/read-only by default');
assert.match(js,/correctionTaxOverrideEnabled\.checked[\s\S]*correctionTaxOverrideAmount\.readOnly = !enabled/,'override requires explicit enablement');
assert.match(js,/overrideEnabled && \(!Number\.isFinite\(overrideAmount\)[\s\S]*!overrideReason\)/,'override explanation is mandatory');
assert.match(js,/correctedRecordFromForm[\s\S]*vendor_name[\s\S]*shipping_charged[\s\S]*shipping_cost[\s\S]*miles_driven/,'income and expense business fields are sent as a full record');
assert.match(js,/financialChange \? 'Reversal and replacement' : 'Metadata-only correction'/,'client previews the accounting path');
assert.match(sql,/v_kind:=case when exists[\s\S]*v_financial_keys[\s\S]*'reversal_replacement' else 'metadata_only'/,'server independently classifies changes');
assert.match(sql,/if v_kind='metadata_only' then[\s\S]*'correct_entry_metadata'[\s\S]*else[\s\S]*'correct_entry_reversal'[\s\S]*'correct_entry_replacement'/,'metadata writes one row; financial writes reversal and replacement');
assert.match(sql,/insert into public\.finance_correction_receipts[\s\S]*return jsonb_build_object/,'atomic transaction records correction receipt and result');
assert.match(sql,/p_expected_effective_posted_at[\s\S]*is distinct from p_expected_effective_posted_at[\s\S]*40001/,'optimistic concurrency is enforced');
assert.match(sql,/where command_identity=p_correlation_id[\s\S]*'idempotent',true/,'retries return the receipt without duplicates');
assert.match(sql,/v_tax:=v_calculated_tax/,'tax defaults to server calculation');
assert.match(sql,/p_tax_override_enabled[\s\S]*p_tax_override_reason[\s\S]*finance_adjustment_value\(p_corrected_record,'sales_tax_collected'\)/,'tax override is controlled and audited');
assert.match(sql,/-v_effective_taxable[\s\S]*-coalesce\(v_effective\.sales_tax_collected/,'reversal offsets taxable sales and tax');
assert.match(js,/function reportingEntries[\s\S]*report_transaction_count/,'reporting consumes one server-resolved row per original');
assert.match(js,/Correction audit[\s\S]*Changed:[\s\S]*Group:[\s\S]*Original:/,'audit trail is visible');
assert.match(sql,/revoke insert on table public\.financial_entries from public,anon,authenticated/,'browser table INSERT is revoked');
assert.match(js,/create_manual_financial_entry/,'manual creation uses controlled RPC');
assert.doesNotMatch(js,/from\('financial_entries'\)\.(insert|update|delete)/,'browser performs no financial_entries mutation');
assert.match(sql,/alter table public\.finance_correction_receipts enable row level security/,'receipt RLS remains enabled');
assert.match(sql,/security definer set search_path=public,pg_temp/,'RPC has fixed search path');
assert.doesNotMatch(sql,/grant update[^;]*financial_entries/i,'no Finance UPDATE privilege is granted');
assert.match(matrix,/Date, category[\s\S]*Destination county[\s\S]*Tax rate[\s\S]*Shipping cost[\s\S]*Original ID/,'field matrix documents applicability/classification');
assert.equal(+(20.50*6.5/100).toFixed(2),1.33,'OP-000010 canonical tax rounds to 1.33');
console.log('Full-record Finance correction assertions passed.');
