const assert = require('node:assert/strict');
const fs = require('node:fs');
const orders = fs.readFileSync('orders-admin.html','utf8');
const finance = fs.readFileSync('finance-pro.js','utf8');
const financeHtml = fs.readFileSync('finance-pro.html','utf8');
const quote = fs.readFileSync('quote.js','utf8');
const sql = fs.readFileSync('supabase/migrations/202608010003_authoritative_order_finance_tax_metadata.sql','utf8');
const fixture = fs.readFileSync('tests/orders-finance-shipping-charged.test.js','utf8');

assert.match(orders,/id="orderDestinationCounty"[\s\S]*<option value="Portage">Portage<\/option>/,'Orders Admin uses controlled Ohio counties');
assert.match(orders,/id="orderSalesTaxRate" type="number" min="0" max="20"/,'Orders Admin captures bounded rate');
assert.match(orders,/destination_county: \$\('orderDestinationCounty'\)[\s\S]*sales_tax_rate: \$\('orderSalesTaxRate'\)\?\.value === '' \? null : Number/,'save payload retains county and explicit zero rate');
assert.match(orders,/validateOrderTaxMetadata\(payload\)/,'Order saves validate tax metadata');
assert.match(orders,/Math\.round\(\(subtotal \* rate \+ Number\.EPSILON\) \* 100\) \/ 100/,'Order preview uses cent rounding');
assert.match(quote,/destination_county: document\.getElementById\('salesTax'\)\?\.dataset\.taxCounty \|\| null/,'Quote accepted totals retain controlled county');
assert.match(sql,/capture_accepted_order_tax_metadata[\s\S]*new\.destination_county:=coalesce\(new\.destination_county,v_county\)[\s\S]*new\.sales_tax_rate:=coalesce/,'accepted Quote metadata reaches new Order');
assert.match(sql,/get_order_invoice_snapshot\(p_order_id uuid\)[\s\S]*'tax_metadata'[\s\S]*'destination_county'[\s\S]*'tax_rate'[\s\S]*'taxable_subtotal'[\s\S]*'tax_amount'/,'invoice snapshot exposes tax metadata');
assert.match(sql,/apply_order_tax_metadata_to_finance_post[\s\S]*new\.destination_county:=v_county; new\.sales_tax_rate:=v_rate; new\.taxable_sales:=v_taxable; new\.sales_tax_collected:=v_tax/,'server-owned posting carries metadata');
assert.match(sql,/FINANCE_TAX_METADATA_UNRESOLVED: taxable Order has tax but no rate/,'posting rejects collected tax without rate');
assert.match(financeHtml,/id="correctionDestinationCounty"[\s\S]*id="correctionSalesTaxRate"[\s\S]*id="correctionCalculatedTax" type="number" readonly/,'correction UI exposes county/rate but not editable tax');
assert.match(finance,/const calculated = exempt \? 0 : \+\(\(taxable \* rate\) \/ 100\)\.toFixed\(2\)/,'correction preview calculates tax canonically');
assert.match(finance,/correct_financial_entry/,'metadata uses the unified controlled RPC');
assert.match(sql,/v_tax:=case when coalesce\(p_tax_exempt,false\) then 0 else round\(v_taxable\*p_sales_tax_rate\/100,2\) end/,'database calculates tax and never trusts browser tax');
assert.match(sql,/v_delta:=v_tax-coalesce\(v_original\.sales_tax_collected,0\)/,'rate correction records only tax delta');
assert.match(sql,/values\(v_actor,v_original\.type,p_correction_date[\s\S]*,0,0,100,0,0,v_delta/,'metadata correction creates no sales delta');
assert.match(sql,/public\.is_ohio_county\(p_destination_county\)/,'invalid county rejects');
assert.match(sql,/p_tax_exempt,false\) and \(p_sales_tax_rate<>0[\s\S]*p_tax_exempt_reason/,'contradictory exemption rejects');
assert.match(finance,/function reportingEntries[\s\S]*report_transaction_count/,'reporting consumes the authoritative effective projection and excludes correction transactions');
assert.match(sql,/revoke all on function public\.append_finance_tax_metadata_correction[\s\S]*grant execute[\s\S]*to authenticated,service_role/,'RPC grants are narrow');
assert.doesNotMatch(finance,/from\('financial_entries'\)\.update/,'no direct Finance PATCH returns');
assert.doesNotMatch(sql,/grant update[^;]*financial_entries to authenticated/i,'no Finance table UPDATE grant');
assert.match(sql,/alter table public\.financial_entries add column if not exists taxable_sales numeric/,'taxable sales is distinct from gross total');
assert.match(fixture,/taxable_subtotal: 20\.50[\s\S]*tax_rate: 6\.5[\s\S]*tax: 1\.33[\s\S]*final_total: 21\.83/,'OP-000010 authority fixture remains 20.50 + 1.33 = 21.83');
console.log('Finance tax metadata authority assertions passed.');
