const assert=require('node:assert/strict');
const fs=require('node:fs');
const A=require('../js/job-asset-model.js');
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
assert.equal(A.safeStoragePath(owner,id,2,'../../Client Part.STL'),`${owner}/${id}/r2/${id}.stl`,'user filename never becomes the path');
assert.throws(()=>A.safeStoragePath(owner,id,1,'payload.exe'),/not allowed/);
for(const name of ['part.f3d','part.step','part.stl','part.3mf','photo.jpg','guide.pdf'])assert.equal(A.validateFile({name,size:1}),true);
for(const file of [{name:'bad.exe',size:1},{name:'empty.stl',size:0},{name:'huge.stl',size:A.MAX_FILE_SIZE+1}])assert.throws(()=>A.validateFile(file));
const links=A.normalizeLinks([{record_type:'recipe',record_key:'r1',asset_revision_id:id},{record_type:'production_job',record_key:'j1',asset_revision_id:id},{record_type:'recipe',record_key:'r1'}]);
assert.equal(links.length,2,'one immutable revision supports multiple record links without duplicates');
const first=A.buildMetadata({id,owner_id:owner,filename:'part.stl',storage_path:A.safeStoragePath(owner,id,1,'part.stl'),mime_type:'model/stl',category:'stl',file_size:12,revision:1,sha256:'a'.repeat(64),links});
assert.equal(first.links[1].record_key,'j1','metadata linkage is retained');
const second=A.nextRevision(first,{id:'33333333-3333-4333-8333-333333333333',filename:'part-v2.stl'});
assert.equal(second.revision,2);assert.equal(second.revision_group_id,id);assert.equal(first.revision,1,'historical asset snapshot is not rewritten');
assert.equal(A.currentVersions([first,second])[0].id,second.id,'newest active version selected');
assert.equal(A.currentVersions([first,A.archive(second)])[0].id,first.id,'archive removes revision from active selection');
assert.equal(A.archive(second,false).status,'active','archive can be restored');
assert.equal(A.duplicateKey(first),A.duplicateKey({...first,filename:'renamed.stl'}),'duplicate prevention uses content identity');
assert.equal(A.deepLink(links[0]),'product-recipes.html?recipe=r1');assert.equal(A.deepLink(links[1]),'production-control.html?job=j1');
const migration=fs.readFileSync(require.resolve('../supabase/migrations/202607160007_job_asset_management.sql'),'utf8');
assert.match(migration,/enable row level security/g);assert.match(migration,/to authenticated/g);assert.doesNotMatch(migration,/to anon|public\s*=\s*true/i,'unauthorized/public access is rejected');
assert.match(migration,/storage\.foldername\(name\).*auth\.uid/,'storage paths are owner-scoped');
assert.match(migration,/unique\(asset_revision_id,record_type,record_key\)/,'duplicate links are prevented');
for(const page of ['product-recipes.html','production-control.html','orders-admin.html','customer-360.html'])assert.match(fs.readFileSync(require.resolve(`../${page}`),'utf8'),/data-job-assets/);
assert.doesNotMatch(fs.readFileSync(require.resolve('../js/job-assets-ui.js'),'utf8'),/localStorage/,'Supabase remains remote-authoritative');
console.log('job asset model and access-policy assertions passed');
