const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
require('../js/tax-rate.js');require('../js/order-line-items.js');require('../js/quote-pricing.js');
const P=require('../js/order-pricing.js');
const modulePath=process.env.PGLITE_MODULE;
test('pricing migration: unpaid revisions, payments, Finance, tracker, authorization and atomicity', {skip:!modulePath}, async()=>{
 const {PGlite}=require(modulePath);const db=new PGlite();
 await db.exec(fs.readFileSync('tests/sql/order-pricing-fixture.sql','utf8'));
 const helper=fs.readFileSync('supabase/migrations/202608020003_repair_finance_adjustment_helper_resolution.sql','utf8');
 await db.exec(helper.slice(helper.indexOf('create or replace function public.finance_adjustment_value'),helper.indexOf('create or replace function public.correct_financial_entry')));
 await db.exec(fs.readFileSync('supabase/migrations/20260928150008_order_line_items_and_pricing_revisions.sql','utf8'));
 const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 await db.query('insert into auth.users values ($1),($2)',[owner,other]);
 const items=[{id:'dragon',description:'Dragon',quantity:5,unit_price:3},{id:'puppy',description:'Puppy',quantity:1,unit_price:2}];
 const original=P.snapshot(items,{taxRate:7,shippingDeferred:true});
 await db.query("insert into orders(id,user_id,order_number,source_quote_number,quantity,order_total,deposit_amount,balance_amount,payment_status,status,updated_at,sales_tax_rate,destination_county,order_title) values($1,$2,'OP-000198','Q-000304',6,18.19,0,18.19,'unpaid','ready_to_print',now(),7,'Portage','Mixed toys')",[id,owner]);
 await db.query("insert into quote_accepted_commercial_snapshots values($1,'OP-000198','Q-000304',$2)",[owner,JSON.stringify({invoice_totals_schema_version:1,invoice_totals:original})]);
 await db.query("insert into order_tracking_public(user_id,order_number,order_total,payment_status) values($1,'OP-000198',18.19,'unpaid')",[owner]);
 const row=async()=> (await db.query('select * from orders where id=$1',[id])).rows[0];
 const pendingInvoice=(await db.query('select get_order_invoice_snapshot_base($1) invoice',[id])).rows[0].invoice;
 assert.equal(pendingInvoice.reconciliation_status,'verified','shipping-pending invoice stays viewable and editable');
 await db.exec('create trigger invoice_authority before insert on financial_entries for each row execute function apply_invoice_authority_to_finance_post();create trigger zz_tax before insert on financial_entries for each row execute function apply_order_tax_metadata_to_finance_post();');
 await assert.rejects(db.query("insert into financial_entries(user_id,order_id,order_number,finance_command) values($1,$2,'OP-000198','post_order_income')",[owner,id]),/FINANCE_SHIPPING_PENDING/);
 const totals=P.snapshot([items[0]],{taxRate:7,shipping:6});
 let before=await row();
 const revise=async(command,t=totals,stamp=before.updated_at)=>db.query('select * from revise_order_pricing($1,$2,$3,$4,$5)',[id,stamp,command,'Puppy canceled; shipping added',JSON.stringify(t)]);
 await revise('first');
 let after=await row();assert.equal(Number(after.order_total),22.47);assert.equal(Number(after.balance_amount),22.47);assert.equal(after.payment_status,'unpaid');
 let inv=(await db.query('select get_order_invoice_snapshot_base($1) invoice',[id])).rows[0].invoice;
 assert.equal(inv.reconciliation_status,'verified');assert.equal(inv.accepted_commercial_breakdown.shipping,6);assert.equal(inv.current_payment_state.amount_paid,0);
 const tracking=(await db.query("select * from public_order_tracking_lookup('Q-304')")).rows[0];
 assert.equal(tracking.order_number,'OP-000198');assert.equal(Number(tracking.order_total),22.47);assert.equal(Number(tracking.shipping_charged),6);
 assert.equal((await db.query("select snapshot->'invoice_totals' totals from quote_accepted_commercial_snapshots")).rows[0].totals.final_total,18.19);
 await revise('first');assert.equal((await db.query('select count(*) n from order_pricing_revisions')).rows[0].n,1);
 await assert.rejects(revise('stale'),/changed/);
 before=after;
 await assert.rejects(revise('forged',{...totals,final_total:1}),/reconcile/);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
 await assert.rejects(revise('other-owner'),/not found/);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 assert.equal((await db.query("select has_function_privilege('anon','public.revise_order_pricing(uuid,timestamptz,text,text,jsonb)','execute') allowed")).rows[0].allowed,false);
 await assert.rejects(db.query("update order_pricing_revisions set reason='erased'"),/immutable/);
 // A requested deposit is not a payment. Then simulate an existing partial receipt.
 await db.query("update orders set payment_status='deposit_due',deposit_amount=5,balance_amount=17.47 where id=$1",[id]);before=await row();await revise('deposit-due');
 assert.equal(Number((await row()).balance_amount),22.47);
 await db.query("update orders set payment_status='deposit_paid',balance_amount=12.47 where id=$1",[id]);before=await row();await revise('partial',P.snapshot([items[0]],{taxRate:7,shipping:8}));
 after=await row();assert.equal(Number(after.order_total),24.61);assert.equal(Number(after.balance_amount),14.61);
 // Reducing below paid amount retains credit, even across subsequent revisions.
 before=after;await revise('credit',P.snapshot([{...items[0],quantity:1}],{taxRate:7}));
 inv=(await db.query('select get_order_invoice_snapshot_base($1) invoice',[id])).rows[0].invoice;
 assert.equal(inv.credit_amount,6.79);assert.equal(inv.current_payment_state.amount_paid,10);
 before=await row();await revise('credit-again',P.snapshot([{...items[0],quantity:2}],{taxRate:7}));
 inv=(await db.query('select get_order_invoice_snapshot_base($1) invoice',[id])).rows[0].invoice;assert.equal(inv.current_payment_state.amount_paid,10);
 before=await row();await revise('final',totals);
 // Execute the actual Finance posting triggers with the revised snapshot.
 const finance=(await db.query("insert into financial_entries(user_id,order_id,order_number,finance_command) values($1,$2,'OP-000198','post_order_income') returning *",[owner,id])).rows[0];
 assert.equal(Number(finance.amount),15);assert.equal(Number(finance.shipping_charged),6);assert.equal(Number(finance.sales_tax_collected),1.47);
 assert.equal(Number(finance.amount)+Number(finance.shipping_charged)+Number(finance.sales_tax_collected),22.47);
 before=await row();await assert.rejects(revise('after-finance'),/Finance/);
 const corrected={...finance,amount:15,original_amount:15,shipping_charged:8,entry_date:'2026-09-28',tax_exempt_sale:false};
 const correction=(await db.query("select correct_financial_entry($1,$2,array['shipping_charged'],'Shipping adjusted',$3,false,null,'finance-shipping-correction') result",[finance.id,JSON.stringify(corrected),finance.posted_at])).rows[0].result;
 assert.equal(correction.effective_record.shipping_charged,8);
 assert.equal(correction.effective_record.sales_tax_collected,1.61,'shipping-only Finance corrections recalculate tax');
 assert.equal((await db.query('select sales_tax_collected from financial_entries where id=$1',[finance.id])).rows[0].sales_tax_collected,'1.47','original Finance posting stays unchanged');
 await db.exec('delete from financial_entries; delete from order_tracking_public;');before=await row();
 const count=(await db.query('select count(*) n from order_pricing_revisions')).rows[0].n;
 await assert.rejects(revise('no-tracker'),/Tracking projection/);
 assert.equal((await db.query('select count(*) n from order_pricing_revisions')).rows[0].n,count);
 await db.close();
});
