import type { DraftPlayer, PlannedPick, Position, SeasonSetup } from './models'

export const POSITION_LABELS: Partial<Record<Position, string>> = {
  QB: 'Quarterback', RB: 'Running Back', WR: 'Wide Receiver', TE: 'Tight End', DST: 'Defense / Special Teams', K: 'Kicker',
  DL: 'Defensive Line', DT: 'Defensive Tackle', DE: 'Defensive End', LB: 'Linebacker', DB: 'Defensive Back', CB: 'Cornerback', S: 'Safety', P: 'Punter', HC: 'Head Coach',
}
export type LeagueSettingSafety = 'SAFE' | 'START_NEW_DRAFT' | 'UNSUPPORTED'
export interface LeagueSettingEdit { scoringLabel:string; ppr:number; draftType:SeasonSetup['draft']['draftType']; pickTimerSeconds:number|null; teamCount:number; rounds:number }
export function settingSafety(field:keyof LeagueSettingEdit,picksExist:boolean):LeagueSettingSafety { if(!picksExist)return'SAFE';if(field==='scoringLabel'||field==='ppr'||field==='pickTimerSeconds')return'SAFE';if(field==='teamCount'||field==='rounds')return'START_NEW_DRAFT';return'UNSUPPORTED' }
export function applyLeagueSettingEdit(setup:SeasonSetup,edit:LeagueSettingEdit,picksExist:boolean):SeasonSetup { const old:LeagueSettingEdit={scoringLabel:setup.settings.scoringLabel,ppr:setup.settings.ppr,draftType:setup.draft.draftType,pickTimerSeconds:setup.draft.pickTimerSeconds,teamCount:setup.draft.teamCount,rounds:setup.draft.rounds};const blocked=(Object.keys(edit) as (keyof LeagueSettingEdit)[]).filter(key=>settingSafety(key,picksExist)!=='SAFE'&&edit[key]!==old[key]);if(blocked.length)throw new Error(`${blocked.join(', ')} requires Start New Draft and was not changed.`);return{...setup,settings:{...setup.settings,scoringLabel:edit.scoringLabel,ppr:edit.ppr},draft:{...setup.draft,draftType:edit.draftType,pickTimerSeconds:edit.pickTimerSeconds,teamCount:edit.teamCount,rounds:edit.rounds}} }
export type PickAttention='ON_THE_CLOCK'|'YOU_ARE_NEXT'|'WAITING'
export function pickAttention(plan:PlannedPick[],current:PlannedPick|null,userTeamId:string):PickAttention { if(!current)return'WAITING';if(current.currentTeamId===userTeamId)return'ON_THE_CLOCK';return plan.find(p=>p.kind==='live'&&p.sequence>current.sequence)?.currentTeamId===userTeamId?'YOU_ARE_NEXT':'WAITING' }
export type PlayerAlertKind='URGENT'|'INJURY'|'INACTIVE'|'NEWS'
export interface PlayerAlert {kind:PlayerAlertKind;severity:'HIGH'|'MEDIUM'|'LOW';icon:string;summary:string;source?:string;timestamp?:string}
export function playerAlert(player:DraftPlayer):PlayerAlert|undefined {const intel=player.playerIntelligence;if(!intel)return;const status=intel.availabilityStatus??'UNKNOWN',injury=intel.injury,news=[...intel.newsItems].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt))[0],injurySummary=injury?[injury.status.replaceAll('_',' '),injury.bodyArea,injury.practiceParticipation].filter(Boolean).join(' · '):undefined;if(['SUSPENDED','OUT','OUT_FOR_SEASON','IR','PUP'].includes(status))return{kind:'INACTIVE',severity:'HIGH',icon:'⛔',summary:injurySummary??`Status: ${status.replaceAll('_',' ')}`,source:injury?.source,timestamp:injury?.updatedAt??intel.lastUpdated};if(injury)return{kind:'INJURY',severity:status==='DOUBTFUL'?'HIGH':status==='QUESTIONABLE'?'MEDIUM':'LOW',icon:'🩹',summary:injurySummary!,source:injury.source,timestamp:injury.updatedAt};if(news?.materiality==='HIGH')return{kind:'URGENT',severity:'HIGH',icon:'🚨',summary:news.summary,source:news.source,timestamp:news.publishedAt};if(news)return{kind:'NEWS',severity:news.materiality==='MED'?'MEDIUM':'LOW',icon:'📰',summary:news.summary,source:news.source,timestamp:news.publishedAt}}
