import type{DraftPlayer,Position,SeasonSetup}from'./models';import{believelandScoringRules}from'./scoring';
const believeland=['Brandon Whipkey','Tom Hipwell','Tom Levak','John Rimar','Mark Seger','John McDougal','Gary Bush','Rob Siwicki','Matt Nero','Michael Olesh','Jim McHale','Shaun Shamrock'];
const robocop=['Corey Huffman','Mike Ciambrone','Patrick McFall','John McDougal','Chris Gorse','Rob Siwicki','John Rimar','G Mark Kokosko','Matt Rimar','Jarred Grzywna','Thomas Levak','Brandon Bergstrom'];
export const roboOrder=['Brandon Bergstrom','Chris Gorse','John Rimar','John McDougal','Matt Rimar','Corey Huffman','Jarred Grzywna','Rob Siwicki','Thomas Levak','Mike Ciambrone','Patrick McFall','G Mark Kokosko'];
const keeperMap:Record<string,string[]>= {'Patrick McFall':['Omarion Hampton','Quinshon Judkins','CeeDee Lamb'],'John McDougal':['Puka Nacua','Terry McLaurin','Kenneth Walker III'],'Chris Gorse':['Cam Skattebo','Breece Hall','Derrick Henry'],'Rob Siwicki':['Josh Allen','Drake London','Jaxon Smith-Njigba'],'John Rimar':['Malik Nabers','A.J. Brown','Garrett Wilson'],'G Mark Kokosko':["Ja'Marr Chase",'Justin Jefferson','Christian McCaffrey'],'Matt Rimar':['Tetairoa McMillan','Brock Bowers',"De'Von Achane"],'Jarred Grzywna':['Saquon Barkley','Chris Olave','Lamar Jackson']};
const norm=(x:string)=>x.trim().toLowerCase();
export function seedSetup(slug:'believeland'|'robocop'):SeasonSetup{const robo=slug==='robocop',names=robo?robocop:believeland,leagueId=`league-${slug}`,seasonId=`season-${slug}-2026`;const managers=names.map((displayName,i)=>({id:`manager-${slug}-${i+1}`,leagueId,displayName,active:true}));const teams=managers.map((m,i)=>({id:`team-${slug}-${i+1}`,seasonId,managerId:m.id,active:true}));const team=(name:string)=>teams.find(t=>managers.find(m=>m.id===t.managerId)?.displayName===name)!;const order=robo?roboOrder:names;const draftSlots=order.map((name,i)=>({seasonId,slot:i+1,originalTeamId:team(name).id}));const specs:[string,number,Position[],('starter'|'bench'|'ir')][]=robo?[['QB',1,['QB'],'starter'],['RB',2,['RB'],'starter'],['WR',3,['WR'],'starter'],['TE',1,['TE'],'starter'],['FLEX',1,['RB','WR','TE'],'starter'],['IDP',2,['DL','LB','DB'],'starter'],['D/ST',1,['DST'],'starter'],['K',1,['K'],'starter'],['Bench',8,[],'bench'],['IR',1,[],'ir']]:[['QB',1,['QB'],'starter'],['RB',2,['RB'],'starter'],['WR',2,['WR'],'starter'],['TE',1,['TE'],'starter'],['FLEX',2,['RB','WR','TE'],'starter'],['D/ST',1,['DST'],'starter'],['K',1,['K'],'starter'],['Bench',6,[],'bench'],['IR',2,[],'ir']];const keepers=robo?Object.entries(keeperMap).flatMap(([name,players])=>players.map((displayName,i)=>({id:`keeper-${norm(displayName).replace(/[^a-z0-9]/g,'-')}`,seasonId,teamId:team(name).id,keeperSlot:i+1,player:{id:`player-${norm(displayName).replace(/[^a-z0-9]/g,'-')}`,canonicalPlayerId:null,displayName,normalizedName:norm(displayName)},status:'provisional' as const}))):[];return{league:{id:leagueId,name:robo?'RoboCop':'Believeland',slug},season:{id:seasonId,leagueId,year:2026,name:`${robo?'RoboCop':'Believeland'} 2026`},settings:{seasonId,scoringLabel:robo?'Head-to-Head Points · Custom 0.5 PPR':'Head-to-Head Points, Point Per Reception · Custom',ppr:robo?.5:1,idpEnabled:robo,scoringRules:robo?undefined:believelandScoringRules,metadata:robo?undefined:{leagueFormat:'League Manager',publicLeague:false,autoReactivate:false,lineupProtection:'Off',playerUniverse:'NFL',observeUndroppableList:true,keepers2026:false,keepers2027:false}},managers,teams,rosterSlots:specs.map(([label,count,eligible,kind],i)=>({id:`slotdef-${slug}-${i}`,seasonId,label,count,eligible,kind})),positionLimits:(robo?[['QB',3],['RB',5],['WR',8],['TE',3],['DST',3],['K',3]]as[Position,number][]:[['QB',4],['RB',8],['WR',8],['TE',3],['DST',3],['K',3],['DT',0],['DE',0],['LB',0],['CB',0],['S',0],['P',0],['HC',0]]as[Position,number][]).map(([position,maximum])=>({seasonId,position,maximum})),draft:{seasonId,teamCount:12,draftType:robo?'online':'offline',draftDate:null,snake:true,rounds:17,pickTimerSeconds:robo?90:null,keeperCount:robo?3:0,liveStartRound:robo?4:1,pickTradingEnabled:robo,orderStatus:robo?'locked':'assigned'},draftSlots,ownership:[],keepers,keeperLock:{seasonId,status:'provisional',deadline:robo?'2026-08-23T20:00:00Z':null,lockedAt:null,lockedBy:null,audit:[]}}}
export function playerPool(count=240):DraftPlayer[]{const positions:Position[]=['QB','RB','WR','TE','DST','K','DL','LB','DB'];const synthetic=Array.from({length:count},(_,i)=>({id:`synthetic-${i+1}`,canonicalPlayerId:null,displayName:`Test Player ${String(i+1).padStart(3,'0')}`,normalizedName:`test player ${i+1}`,position:positions[i%positions.length]}));const keeperPlayers=seedSetup('robocop').keepers.map((k,i)=>({...k.player,position:(['RB','RB','WR','WR','WR','RB','RB','RB','RB','QB','WR','WR']as Position[])[i%12]}));return [...keeperPlayers,...synthetic]}
export{believeland,robocop};
