import type{ArgumentRequestContext,ConversationMessage,DraftPhilosophy,DraftPreference,DraftUserContext,OffseasonBriefingContext,PlayerInterest,PlayerInterestState,Position,StrategicIntent,StrategicIntentCategory,StrategicIntentWindow}from'./models';
const now=()=>new Date().toISOString();const id=()=>crypto.randomUUID();
export const emptyPhilosophy=(leagueId:string,seasonId:string):DraftPhilosophy=>({id:`philosophy:${seasonId}`,leagueId,seasonId,preferences:[],freeformNotes:'',onboardingStatus:'NOT_STARTED',updatedAt:now()});
export function setPreference(profile:DraftPhilosophy,input:Omit<DraftPreference,'id'|'updatedAt'>):DraftPhilosophy{const existing=profile.preferences.find(x=>x.category===input.category);const preference={...input,id:existing?.id??id(),updatedAt:now()};return{...profile,preferences:[...profile.preferences.filter(x=>x.category!==input.category),preference],onboardingStatus:'IN_PROGRESS',updatedAt:now()}}
export const removePreference=(profile:DraftPhilosophy,preferenceId:string):DraftPhilosophy=>({...profile,preferences:profile.preferences.filter(x=>x.id!==preferenceId),updatedAt:now()});
export const setInterest=(scope:{leagueId:string;seasonId:string},playerId:string,state:PlayerInterestState,note?:string,existing?:PlayerInterest):PlayerInterest=>({id:existing?.id??`interest:${scope.seasonId}:${playerId}`,playerId,state,note:note?.trim()||undefined,...scope,updatedAt:now()});
export const createIntent=(scope:{leagueId:string;seasonId:string},text:string,category:StrategicIntentCategory='CUSTOM',window?:StrategicIntentWindow):StrategicIntent=>({id:id(),...scope,text:text.trim(),category,window,status:'ACTIVE',createdAt:now(),updatedAt:now()});
export const updateIntent=(intent:StrategicIntent,changes:Partial<Pick<StrategicIntent,'text'|'category'|'window'|'status'>>):StrategicIntent=>({...intent,...changes,updatedAt:now()});
export const message=(scope:{leagueId:string;seasonId:string},type:ConversationMessage['type'],text:string,extra:Partial<ConversationMessage>={}):ConversationMessage=>({id:id(),...scope,type,text,createdAt:now(),...extra});
export const argumentContext=(input:Omit<ArgumentRequestContext,'id'|'createdAt'>):ArgumentRequestContext=>({id:id(),createdAt:now(),...input});
export function briefingContext(input:{leagueId:string;seasonId:string;draftSessionId?:string;playerId:string;position:Position;team?:string;philosophy:DraftPhilosophy;interest?:PlayerInterest}):OffseasonBriefingContext{return{id:id(),leagueId:input.leagueId,seasonId:input.seasonId,draftSessionId:input.draftSessionId,playerId:input.playerId,position:input.position,team:input.team,philosophyPreferenceIds:input.philosophy.preferences.map(x=>x.id),playerInterestId:input.interest?.id,createdAt:now()}}
export const userContext=(philosophy:DraftPhilosophy,playerInterests:PlayerInterest[],strategicIntents:StrategicIntent[],conversation:ConversationMessage[]):DraftUserContext=>({philosophy,playerInterests,strategicIntents,recentConversation:conversation.slice(-20)});
export const AI_PLACEHOLDERS={ARGUE:'Deterministic countercase is available from the current recommendation card.',BRIEF:'Offseason briefing requires current NFL context and is not enabled yet.'}as const;
