import type { DraftPhilosophy, DraftPlayer, PlayerInterest, Position, StrategicIntent } from '../domain/models';
import { philosophyProfile, philosophySummary } from '../domain/draft-philosophy';

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[character]!));

export const CORE_POSITION_STRATEGIES: { position: Position; label: string }[] = [
  { position: 'QB', label: 'Quarterback' }, { position: 'RB', label: 'Running back' },
  { position: 'WR', label: 'Wide receiver' }, { position: 'TE', label: 'Tight end' },
];

export const positionCategory = (position: Position) => `${position}_STRATEGY`;

export function philosophyWorkspaceMarkup(input: { slug: string; philosophy: DraftPhilosophy; interests: PlayerInterest[]; intents: StrategicIntent[]; players: DraftPlayer[] }): string {
  const { slug, philosophy, interests, intents, players } = input;
  const profile = philosophyProfile(philosophy);
  const select=(name:string,value:string,options:string[])=>`<select name="${name}">${options.map(option=>`<option value="${option}" ${value===option?'selected':''}>${option.replaceAll('_',' ')}</option>`).join('')}</select>`;
  const activeIntents = intents.filter(item => item.status === 'ACTIVE');
  const preference = (category: string) => philosophy.preferences.find(item => item.category === category);
  const configured = CORE_POSITION_STRATEGIES.map(({ position, label }) => ({ position, label, value: preference(positionCategory(position))?.value }));
  const playerName = (id: string) => players.find(player => player.id === id)?.displayName ?? 'Player unavailable';
  const interestGroups: { state: PlayerInterest['state']; label: string }[] = [
    { state: 'INTERESTED', label: 'Interested' }, { state: 'WATCH', label: 'Watching' }, { state: 'FADE', label: 'Fades' },
  ];
  return `<main class="philosophy-workspace strategy-control-center"><header class="strategy-header"><a href="#/${slug}">← League</a><p class="eyebrow">STRATEGY CONTROL CENTER</p><h1>Draft Philosophy</h1><p>Set durable draft preferences, review player signals, and manage temporary draft-night instructions.</p></header>
  <section class="draft-plan"><div><small>YOUR DRAFT PLAN</small><h2>${philosophy.preferences.length ? 'CONFIGURED BUILD' : 'NO PLAN CONFIGURED'}</h2></div><div class="plan-grid">${configured.map(item => `<article><b>${item.position}</b><span>${item.value ? escapeHtml(item.value) : 'Not configured'}</span></article>`).join('')}${preference('RISK') ? `<article><b>RISK</b><span>${escapeHtml(preference('RISK')!.value)}</span></article>` : ''}</div></section>
  <section><div class="section-heading"><div><small>AFFECTS DRAFT FIT</small><h2>Position strategy</h2></div><p>These saved position directions are bounded inputs to Draft Fit.</p></div><div class="position-strategy-grid">${configured.map(item => `<form class="position-strategy-card" data-position-form="${item.position}"><div><span class="position-chip position-${item.position.toLowerCase()}">${item.position}</span><h3>${item.label}</h3></div><label>Approach<select name="approach"><option value="">Not configured</option>${['PRIORITY','NORMAL','WAIT','AVOID'].map(value => `<option ${item.value?.toUpperCase().startsWith(value) ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label>Concise instruction<input name="note" maxlength="90" value="${escapeHtml(item.value?.replace(/^(PRIORITY|NORMAL|WAIT|AVOID)\s*[—:-]?\s*/i, '') ?? '')}" placeholder="Optional context"></label><button>SAVE ${item.position}</button></form>`).join('')}</div></section>
  <form id="structured-philosophy-form" class="philosophy-groups"><section><div class="section-heading"><div><small>CORE DRAFT APPROACH</small><h2>Value, risk &amp; reach</h2></div><p>These are bounded tiebreakers. A meaningful tier advantage remains more important.</p></div><div class="philosophy-fields"><label>Core approach${select('coreApproach',profile.coreApproach,['VALUE_FIRST_ADAPTIVE','VALUE_FIRST','BALANCED','NEED_WEIGHTED','AGGRESSIVE_UPSIDE','CONSERVATIVE'])}</label><label>Early risk${select('earlyRisk',profile.earlyRisk,['VERY_SAFE','SAFETY_WITHIN_TIER','BALANCED','PREFER_UPSIDE','AGGRESSIVE_UPSIDE'])}</label><label>Late risk${select('lateRisk',profile.lateRisk,['VERY_SAFE','SAFETY_WITHIN_TIER','BALANCED','PREFER_UPSIDE','AGGRESSIVE_UPSIDE'])}</label><label>Reach tolerance${select('reachTolerance',profile.reachTolerance,['VERY_LOW','LOW','MODERATE','MODERATE_HIGH','HIGH'])}</label></div></section>
  <section><div class="section-heading"><div><small>POSITION STRATEGY</small><h2>Tier-aware position value</h2></div><p>Actual starter and FLEX slots determine roster value; no position quotas are created.</p></div><div class="philosophy-fields"><label>QB${select('qbStrategy',profile.qbStrategy,['ELITE_ADVANTAGE','TIER_VALUE','BALANCED','PREFER_WAITING','LATE_QB'])}</label><label>TE${select('teStrategy',profile.teStrategy,['ELITE_ADVANTAGE','TIER_VALUE_CLIFF','BALANCED','PREFER_WAITING','LATE_TE'])}</label><label>RB workload${select('rbWorkload',profile.rbWorkload,['NEUTRAL','LEAD_ROLE','OPPORTUNITY','RECEIVING','CONTINGENT_UPSIDE'])}</label><label>FLEX / RB-WR depth${select('flexDepth',profile.flexDepth,['LOW','MODERATE','HIGH'])}</label></div></section>
  <section><div class="section-heading"><div><small>DRAFT DYNAMICS</small><h2>Read the room</h2></div><p>Pick gaps, tier depth, and teams selecting before you inform whether to act or wait.</p></div><div class="philosophy-fields"><label>Exploit managers${select('draftRoomExploitation',profile.draftRoomExploitation,['LOW','MODERATE','HIGH'])}</label><label>Scarcity${select('scarcityWeight',profile.scarcityWeight,['LOW','MODERATE','HIGH'])}</label><label>Probability of return${select('returnProbabilityWeight',profile.returnProbabilityWeight,['LOW','MODERATE','HIGH'])}</label><label>Bye weeks${select('byeWeekImportance',profile.byeWeekImportance,['LOW','STAGE_SENSITIVE','MODERATE','HIGH'])}</label></div></section>
  <section><div class="section-heading"><div><small>PERSONAL PREFERENCES</small><h2>Soft modifiers</h2></div><p>Interest and portfolio risk can break close decisions, never override a tier.</p></div><div class="philosophy-fields"><label>Interested influence${select('interestWeight',profile.interestWeight,['NONE','LOW','MODERATE','HIGH'])}</label><label>Roster risk balance${select('rosterRiskBalance',profile.rosterRiskBalance,['NONE','MODERATE','CONTINUOUS'])}</label><label class="wide">Optional conversational summary<textarea name="summary" maxlength="900">${escapeHtml(philosophy.summary??philosophySummary(profile))}</textarea></label><label class="wide">Additional context<input name="note" maxlength="240" value="${escapeHtml(philosophy.freeformNotes)}" placeholder="Optional nuance for the assistant"></label></div><button>SAVE PHILOSOPHY</button></section></form>
  <section class="philosophy-summary"><small>CURRENT PHILOSOPHY SUMMARY</small><p>${escapeHtml(philosophy.summary??philosophySummary(profile))}</p></section>
  <section><div class="section-heading"><div><small>PERSONAL NOTE</small><h2>Player preferences</h2></div><a href="#/${slug}/rankings">OPEN RANKINGS</a></div><div class="interest-summary">${interestGroups.map(group => { const matches = interests.filter(item => item.state === group.state || (group.state === 'INTERESTED' && item.state === 'FAVORITE') || (group.state === 'FADE' && item.state === 'AVOID')); return `<article><h3>${group.label}<span>${matches.length}</span></h3>${matches.map(item => `<a href="#/${slug}/rankings" title="Open Rankings">${escapeHtml(playerName(item.playerId))}</a>`).join('') || '<p>None saved</p>'}</article>`; }).join('')}</div></section>
  <section class="live-adjustments"><div class="section-heading"><div><small>LIVE DRAFT ADJUSTMENTS · AFFECTS DRAFT FIT WHEN POSITION-SPECIFIC</small><h2>Temporary instructions</h2></div><button id="clear-live-adjustments" ${activeIntents.length ? '' : 'disabled'}>CLEAR LIVE ADJUSTMENTS</button></div><p>Conversation-created strategy appears here separately from your durable philosophy.</p><div class="intent-list">${activeIntents.map(item => `<form data-intent-form="${item.id}"><input name="text" value="${escapeHtml(item.text)}" maxlength="140" aria-label="Live adjustment"><button>SAVE</button><button type="button" data-remove-intent="${item.id}">REMOVE</button></form>`).join('') || '<p class="empty-state">No live adjustments.</p>'}</div></section>
  <section class="strategy-reset"><div><h2>Reset philosophy</h2><p>Clears only durable philosophy and AI-context notes. League settings, draft history, rankings, player data, authentication, and live adjustments remain unchanged.</p></div><button id="reset-philosophy">RESET PHILOSOPHY</button></section></main>`;
}
