import type { DraftPhilosophy, DraftPlayer, PlayerInterest, Position, StrategicIntent } from '../domain/models';

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[character]!));

export const CORE_POSITION_STRATEGIES: { position: Position; label: string }[] = [
  { position: 'QB', label: 'Quarterback' }, { position: 'RB', label: 'Running back' },
  { position: 'WR', label: 'Wide receiver' }, { position: 'TE', label: 'Tight end' },
];

export const positionCategory = (position: Position) => `${position}_STRATEGY`;

export function philosophyWorkspaceMarkup(input: { slug: string; philosophy: DraftPhilosophy; interests: PlayerInterest[]; intents: StrategicIntent[]; players: DraftPlayer[] }): string {
  const { slug, philosophy, interests, intents, players } = input;
  const activeIntents = intents.filter(item => item.status === 'ACTIVE');
  const preference = (category: string) => philosophy.preferences.find(item => item.category === category);
  const configured = CORE_POSITION_STRATEGIES.map(({ position, label }) => ({ position, label, value: preference(positionCategory(position))?.value }));
  const playerName = (id: string) => players.find(player => player.id === id)?.displayName ?? 'Player unavailable';
  const interestGroups: { state: PlayerInterest['state']; label: string }[] = [
    { state: 'INTERESTED', label: 'Interested' }, { state: 'WATCH', label: 'Watching' }, { state: 'FADE', label: 'Fades' },
  ];
  return `<main class="philosophy-workspace strategy-control-center"><header class="strategy-header"><a href="#/${slug}">← League</a><p class="eyebrow">STRATEGY CONTROL CENTER</p><h1>Draft Philosophy</h1><p>Set durable draft preferences, review player signals, and manage temporary draft-night instructions.</p></header>
  <section class="draft-plan"><div><small>YOUR DRAFT PLAN</small><h2>${philosophy.preferences.length ? 'CONFIGURED BUILD' : 'NO PLAN CONFIGURED'}</h2></div><div class="plan-grid">${configured.map(item => `<article><b>${item.position}</b><span>${item.value ? escapeHtml(item.value) : 'Not configured'}</span></article>`).join('')}${preference('RISK') ? `<article><b>RISK</b><span>${escapeHtml(preference('RISK')!.value)}</span></article>` : ''}</div></section>
  <section><div class="section-heading"><div><small>AFFECTS DRAFT FIT</small><h2>Position strategy</h2></div><p>These saved position directions are bounded inputs to Draft Fit.</p></div><div class="position-strategy-grid">${configured.map(item => `<form class="position-strategy-card" data-position-form="${item.position}"><div><span class="position-chip position-${item.position.toLowerCase()}">${item.position}</span><h3>${item.label}</h3></div><label>Approach<select name="approach"><option value="">Not configured</option>${['PRIORITY','NORMAL','WAIT','AVOID'].map(value => `<option ${item.value?.toUpperCase().startsWith(value) ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label>Concise instruction<input name="note" maxlength="90" value="${escapeHtml(item.value?.replace(/^(PRIORITY|NORMAL|WAIT|AVOID)\s*[—:-]?\s*/i, '') ?? '')}" placeholder="Optional context"></label><button>SAVE ${item.position}</button></form>`).join('')}</div></section>
  <section><div class="section-heading"><div><small>AI CONTEXT</small><h2>Global draft approach</h2></div><p>These notes guide explanations. They are not presented as deterministic Draft Fit inputs.</p></div><form id="global-strategy-form" class="global-strategy-form"><label>Risk / upside<select name="risk"><option value="">Not configured</option>${['Conservative','Moderate','Upside seeking'].map(value => `<option ${preference('RISK')?.value === value ? 'selected' : ''}>${value}</option>`).join('')}</select></label><label>Roster balance &amp; reach note<input name="note" maxlength="140" value="${escapeHtml(philosophy.freeformNotes)}" placeholder="Optional AI context"></label><button>SAVE APPROACH</button></form></section>
  <section><div class="section-heading"><div><small>PERSONAL NOTE</small><h2>Player preferences</h2></div><a href="#/${slug}/rankings">OPEN RANKINGS</a></div><div class="interest-summary">${interestGroups.map(group => { const matches = interests.filter(item => item.state === group.state || (group.state === 'INTERESTED' && item.state === 'FAVORITE') || (group.state === 'FADE' && item.state === 'AVOID')); return `<article><h3>${group.label}<span>${matches.length}</span></h3>${matches.map(item => `<a href="#/${slug}/rankings" title="Open Rankings">${escapeHtml(playerName(item.playerId))}</a>`).join('') || '<p>None saved</p>'}</article>`; }).join('')}</div></section>
  <section class="live-adjustments"><div class="section-heading"><div><small>LIVE DRAFT ADJUSTMENTS · AFFECTS DRAFT FIT WHEN POSITION-SPECIFIC</small><h2>Temporary instructions</h2></div><button id="clear-live-adjustments" ${activeIntents.length ? '' : 'disabled'}>CLEAR LIVE ADJUSTMENTS</button></div><p>Conversation-created strategy appears here separately from your durable philosophy.</p><div class="intent-list">${activeIntents.map(item => `<form data-intent-form="${item.id}"><input name="text" value="${escapeHtml(item.text)}" maxlength="140" aria-label="Live adjustment"><button>SAVE</button><button type="button" data-remove-intent="${item.id}">REMOVE</button></form>`).join('') || '<p class="empty-state">No live adjustments.</p>'}</div></section>
  <section class="strategy-reset"><div><h2>Reset philosophy</h2><p>Clears only durable philosophy and AI-context notes. League settings, draft history, rankings, player data, authentication, and live adjustments remain unchanged.</p></div><button id="reset-philosophy">RESET PHILOSOPHY</button></section></main>`;
}
