// @vitest-environment jsdom
import {describe,expect,it} from 'vitest';
import {playerDataCenterMarkup} from './player-data-center';
import type {ParsedSource} from '../data/player-data-center';
const staged:ParsedSource={id:'FP_PPR',season:2026,filename:'ppr.csv',timestampConfidence:'LOW',rows:[{source:'FP_PPR',playerName:'Player One',metadata:{}}],mapping:[{original:'Player',normalized:'PLAYER',semantic:'player'}],unknownColumns:['Extra'],warnings:[],errors:[]};
describe('guided Player Data Center',()=>{
 it('presents one primary action and the simple four-step flow',()=>{const html=playerDataCenterMarkup();expect(html).toContain('START PLAYER DATA UPDATE');expect(html).toContain('1. Gather Files');expect(html).toContain('2. Add Files');expect(html).toContain('3. Review');expect(html).toContain('4. Activate')});
 it('supports row upload, concise progress, hidden optional columns, and intent confirmation',()=>{const html=playerDataCenterMarkup(undefined,[staged]);expect(html).toContain('data-source-upload="FP_PPR"');expect(html).toContain('Ready — 1 records found');expect(html).toContain('1 unused columns');expect(html).toContain('Treating this file as FantasyPros PPR Rankings');expect(html).not.toContain('Mapping needs attention')});
 it('shows mapping only for a blocking recognition error',()=>{const html=playerDataCenterMarkup(undefined,[{...staged,errors:['Required Player column was not found.']}]);expect(html).toContain('Mapping needs attention');expect(html).toContain('disabled>ACTIVATE PLAYER DATA')});
 it('advertises PDF as the normal ESPN injury workflow and keeps NFL disabled',()=>{const html=playerDataCenterMarkup();expect(html).toContain('choose Print, select Save as PDF');expect(html).toContain('ESPN NFL Injuries');expect(html).toContain('planned/disabled');expect(html).not.toContain('ESPN Injury Status Complete HTML')});
 it('reports structural ESPN rows separately from non-fantasy provenance and publication time',()=>{const injury={...staged,id:'ESPN_INJURIES' as const,rows:Array.from({length:14},(_,index)=>({source:'ESPN_INJURIES' as const,playerName:`Player ${index}`,metadata:{}})),sourceDate:'2026-08-24T23:59:59Z',sourceDateKind:'CONTENT_DERIVED' as const,pdfCreatedAt:'2026-08-25T17:15:00Z',diagnostics:{duplicateCount:0,skippedRowCount:0,malformedRowCount:0,missingOptionalFields:[],fantasyRelevantCount:5,nonFantasyCount:9}};const html=playerDataCenterMarkup(undefined,[injury]);expect(html).toContain('Ready — 14 ESPN injury records found');expect(html).toContain('5 fantasy-relevant source records');expect(html).toContain('9 non-fantasy roster records retained');expect(html).toContain('Source publication time: Not supplied')});
});
 it('blocks and excludes failed, zero-row, incomplete, and stale-parser sources truthfully',()=>{const failed={...staged,id:'MIKE_CLAY' as const,rows:[],errors:['No rows']},incomplete={...staged,id:'ESPN_INJURIES' as const,diagnostics:{duplicateCount:0,skippedRowCount:0,malformedRowCount:0,missingOptionalFields:[],pagesProcessed:2,pageCount:15}},old={...staged,id:'ESPN_TOP_300' as const,parserVersion:'old',reparseRequired:true};for(const source of [failed,incomplete,old]){const html=playerDataCenterMarkup(undefined,[source]);expect(html).toContain('disabled>ACTIVATE PLAYER DATA');expect(html).toContain('<b>Sources being updated:</b> None');expect(html).not.toContain('100% usable coverage')}expect(playerDataCenterMarkup(undefined,[old])).toContain('Parser updated — please re-add this file')});
