import { describe, expect, it } from 'vitest';
import { activateImport, parseRankingImport, rankingSources, selectPlayerPool } from '../data/player-data';
import { makePick, rebuildDraftState, startDraft } from '../domain/engine';
import type { DraftPlayer } from '../domain/models';
import { playerPool, seedSetup } from '../domain/seeds';
import { emptyPhilosophy } from '../domain/user-context';
import { runRecommendationEngine } from '../intelligence/recommendation-engine';
import { ESPN_CLEAR_VALUE, ESPN_IGNORE_VALUE, deltaLabel, espnReconciliationOptions, filterRankingRows, orderRankingRows, rankingRows, rankingsTableMarkup, type RankingRow, sortRankingRows, locationDefaultAvailable } from './rankings';
const setup=seedSetup('believeland');
const snapshot=activateImport(parseRankingImport('player_name,team,position,overall_rank,position_rank,tier,adp\nTest Player 1,,QB,2,1,1,3\nTest Player 2,,RB,1,1,1,\nTest Player 3,,WR,3,1,2,5',{source:'FantasyPros ECR',updatedAt:'2026-08-15T12:00:00Z',scoringFormat:'PPR'},playerPool()));
const model=()=>{const players=selectPlayerPool(playerPool(),snapshot),context=startDraft(setup,players),state=rebuildDraftState(context),result=runRecommendationEngine({setup,context,state,userTeamId:setup.teams[0].id,userContext:{philosophy:emptyPhilosophy(setup.league.id,setup.season.id),playerInterests:[],strategicIntents:[],recentConversation:[]}});return{players,context,state,result,rows:rankingRows(snapshot,players,state,result.draftFits)}};
describe('rankings workspace model',()=>{
 it('uses only active snapshot rows and defaults to ECR ascending',()=>{const {rows}=model();expect(rows.map(row=>row.market?.overallRank)).toEqual([1,2,3]);expect(rows.every(row=>row.player.playerIntelligence)).toBe(true)});
 it('filters position, search, and availability while ALL retains drafted players',()=>{const {players,context,result}=model(),picked=makePick(context,players.find(player=>player.displayName==='Test Player 2')!.id),state=rebuildDraftState(picked),rows=rankingRows(snapshot,players,state,result.draftFits);expect(filterRankingRows(rows,{position:'QB'}).map(row=>row.player.position)).toEqual(['QB']);expect(filterRankingRows(rows,{search:'player 3'})).toHaveLength(1);expect(filterRankingRows(rows,{availableOnly:true})).toHaveLength(2);expect(filterRankingRows(rows,{})).toHaveLength(3)});
 it('shows offensive ranking fields without an IDP column when IDP authority is disabled',()=>{const {rows}=model(),markup=rankingsTableMarkup(rows);expect(markup).toContain('FP ECR');expect(markup).not.toContain('FP IDP');expect(markup).toContain('DRAFT FIT');expect(rows.find(row=>row.player.displayName==='Test Player 2')?.market?.adp).toBeUndefined();expect(deltaLabel(12).label).toContain('above');expect(deltaLabel(-8).label).toContain('below')});
 it('uses deterministic explanations and only a populated FantasyPros source',()=>{const {rows}=model(),sources=rankingSources(snapshot);expect(rows[0].draftFit?.explanationFacts.length).toBeGreaterThan(0);expect(sources.map(source=>source.id)).toEqual(['FANTASYPROS_ECR']);expect(sources.some(source=>source.id as string==='ESPN')).toBe(false)});
 it('renders unavailable overall ECR and delta as em dashes without inventing ordering',()=>{const missing=structuredClone(snapshot);missing.players.forEach(player=>{player.baselineRank=undefined;player.sourceValues.forEach(value=>{value.overallRank=undefined})});const {players,state,result}=model(),rows=rankingRows(missing,players,state,result.draftFits);expect(rows).toHaveLength(3);expect(rows.every(row=>row.delta==null)).toBe(true);const markup=rankingsTableMarkup(rows);expect(markup).toContain('<span>—</span>');expect(markup).toContain('Draft Fit or source ranking unavailable')});
 it.each(['K','DST'] as const)('keeps %s draftable and shows position rank without synthetic ECR or delta',position=>{const specialist=structuredClone(snapshot);specialist.players=[{...specialist.players[0],canonicalPlayerId:`nfl:${position.toLowerCase()}:test` as never,displayName:`Test ${position}`,normalizedName:`test ${position.toLowerCase()}`,position,baselineRank:undefined,positionRank:4,sourceValues:specialist.players[0].sourceValues.map(value=>({...value,overallRank:undefined,positionRank:4}))}];const players=selectPlayerPool(playerPool(),specialist),context=startDraft(setup,players),state=rebuildDraftState(context),result=runRecommendationEngine({setup,context,state,userTeamId:setup.teams[0].id,userContext:{philosophy:emptyPhilosophy(setup.league.id,setup.season.id),playerInterests:[],strategicIntents:[],recentConversation:[]}}),rows=rankingRows(specialist,players,state,result.draftFits),markup=rankingsTableMarkup(rows);expect(state.available).toContainEqual(players[0]);expect(rows[0]).toMatchObject({market:{overallRank:undefined,positionRank:4},delta:undefined,available:true});expect(markup).toContain(`<span>${position}</span>`);expect(markup).toContain('<span>4</span>');expect(markup).toContain('Draft Fit or source ranking unavailable')});
 it('puts clear and IGNORE first and lists identifiable canonical choices alphabetically',()=>{const {players}=model(),options=espnReconciliationOptions([...players].reverse());expect(options.slice(0,2)).toEqual([{value:ESPN_CLEAR_VALUE,label:'SELECT MATCH...'},{value:ESPN_IGNORE_VALUE,label:'IGNORE — No canonical match'}]);expect(options.slice(2).map(option=>option.label)).toEqual(['Test Player 1 · QB · —','Test Player 2 · RB · —','Test Player 3 · WR · —'])});
 it('sorts unranked canonical players after genuine ESPN ranks and displays an em dash',()=>{const {rows}=model(),ranked=rows.find(row=>row.player.displayName==='Test Player 3')!;ranked.espn={source:'ESPN PPR300',sourceClass:'ANALYST_INTERPRETATION',updatedAt:'2026-08-15T12:00:00Z',overallRank:300,scoringFormat:'PPR',freshness:'FRESH'};const ordered=orderRankingRows(rows,'ESPN');expect(ordered[0]).toBe(ranked);expect(ordered.slice(1).every(row=>row.espn==null)).toBe(true);expect(rankingsTableMarkup(ordered,'ESPN')).toContain('<span>—</span>')});
});

describe('interactive numeric ranking sorting',()=>{
 const sortable=()=>{const rows=model().rows;rows[0].espn={...rows[0].market!,overallRank:7};rows[1].espn={...rows[1].market!,overallRank:2};return rows};
 it.each([['fp','asc',[1,2,3]],['fp','desc',[3,2,1]]] as const)('sorts FantasyPros %s %s without changing ranks',(_key,direction,expected)=>{const rows=sortable(),before=rows.map(x=>x.market?.overallRank);expect(sortRankingRows(rows,{key:'fp',direction}).map(x=>x.market?.overallRank)).toEqual(expected);expect(rows.map(x=>x.market?.overallRank)).toEqual(before)});
 it('sorts ESPN both directions with missing values last',()=>{const rows=sortable();expect(sortRankingRows(rows,{key:'espn',direction:'asc'}).map(x=>x.espn?.overallRank)).toEqual([2,7,undefined]);expect(sortRankingRows(rows,{key:'espn',direction:'desc'}).map(x=>x.espn?.overallRank)).toEqual([7,2,undefined])});
 it.each(['draftFit','deltaFp','positionRank','tier','adp'] as const)('sorts %s ascending and descending deterministically',key=>{const rows=sortable(),asc=sortRankingRows(rows,{key,direction:'asc'}),desc=sortRankingRows(rows,{key,direction:'desc'});expect(asc).toHaveLength(rows.length);expect(desc).toHaveLength(rows.length);expect(sortRankingRows(rows,{key,direction:'asc'})).toEqual(asc)});
 it('renders sortable direction indicators and truthful context defaults',()=>{expect(rankingsTableMarkup(sortable(),'COMPARE',{key:'espn',direction:'desc'})).toContain('▼');expect(locationDefaultAvailable('#/believeland/rankings/draft')).toBe(true);expect(locationDefaultAvailable('#/believeland/rankings')).toBe(false)});
});

describe('ranking interest context',()=>{it('adds and removes the current player-interest badge from a rankings render',()=>{const player={id:'interest-player',canonicalPlayerId:'interest-player',displayName:'Interest Player',normalizedName:'interest player',position:'RB',nflTeam:'CLE'}as DraftPlayer,row={player,market:{overallRank:1,source:'FantasyPros',sourceClass:'ANALYST_INTERPRETATION',updatedAt:'',scoringFormat:'PPR',freshness:'FRESH'},available:true}as RankingRow,interest={id:'interest',leagueId:'league',seasonId:'season',playerId:player.id,state:'INTERESTED',updatedAt:''}as const;expect(rankingsTableMarkup([row],'FANTASYPROS',undefined,[interest])).toContain('Interested');expect(rankingsTableMarkup([row])).not.toContain('Interested')})});
