import type { EspnRankingSource } from '../data/espn-rankings';
import type { PlayerDataSnapshot, RankingValue } from '../data/player-data';
import { rankingSources } from '../data/player-data';
import type { DraftFit } from '../intelligence/recommendation-engine';
import type { DraftPlayer, DraftState, Position } from '../domain/models';

export type RankingMode='FANTASYPROS'|'ESPN'|'COMPARE';
export interface RankingRow { player:DraftPlayer; market:RankingValue; espn?:RankingValue; draftFit?:DraftFit; delta?:number; espnDelta?:number; available:boolean }
export interface RankingFilters { position?:Position; search?:string; availableOnly?:boolean; team?:string; tier?:number }
export const ESPN_IGNORE_VALUE='__IGNORE__';
export const ESPN_CLEAR_VALUE='';
export function espnReconciliationOptions(players:DraftPlayer[]):{value:string;label:string}[]{const canonical=players.filter(player=>player.canonicalPlayerId).sort((a,b)=>a.displayName.localeCompare(b.displayName,undefined,{sensitivity:'base'})||a.position.localeCompare(b.position)||(a.nflTeam??'').localeCompare(b.nflTeam??''));return[{value:ESPN_CLEAR_VALUE,label:'SELECT MATCH...'},{value:ESPN_IGNORE_VALUE,label:'IGNORE — No canonical match'},...canonical.map(player=>({value:player.id,label:`${player.displayName} · ${player.position} · ${player.nflTeam??'—'}`}))]}
export function rankingRows(snapshot:PlayerDataSnapshot|undefined,players:DraftPlayer[],state:DraftState,draftFits:DraftFit[],espn?:EspnRankingSource):RankingRow[]{const source=rankingSources(snapshot).find(item=>item.id==='FANTASYPROS_ECR');if(!source)return[];const byCanonical=new Map(players.filter(player=>player.canonicalPlayerId).map(player=>[player.canonicalPlayerId!,player])),fits=new Map(draftFits.map(fit=>[fit.playerId,fit])),available=new Set(state.available.map(player=>player.id));return[...source.rankings.entries()].flatMap(([canonical,market])=>{const player=byCanonical.get(canonical);if(!player||player.historyOnly||market.overallRank==null)return[];const draftFit=fits.get(player.id),espnValue=espn?.rankings.get(canonical);return[{player,market,espn:espnValue,draftFit,delta:draftFit?market.overallRank-draftFit.rank:undefined,espnDelta:draftFit&&espnValue?.overallRank!=null?espnValue.overallRank-draftFit.rank:undefined,available:available.has(player.id)}]}).sort((a,b)=>a.market.overallRank!-b.market.overallRank!)}
export function orderRankingRows(rows:RankingRow[],mode:RankingMode):RankingRow[]{return[...rows].sort((a,b)=>mode==='ESPN'?(a.espn?.overallRank??Number.MAX_SAFE_INTEGER)-(b.espn?.overallRank??Number.MAX_SAFE_INTEGER):(a.market.overallRank??Number.MAX_SAFE_INTEGER)-(b.market.overallRank??Number.MAX_SAFE_INTEGER))}
export function filterRankingRows(rows:RankingRow[],filters:RankingFilters):RankingRow[]{const search=filters.search?.trim().toLowerCase();return rows.filter(row=>(!filters.position||row.player.position===filters.position)&&(!search||row.player.displayName.toLowerCase().includes(search))&&(!filters.availableOnly||row.available)&&(!filters.team||row.player.nflTeam===filters.team)&&(filters.tier==null||row.market.tier===filters.tier))}
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function deltaLabel(delta:number|undefined,source='FantasyPros ECR'){return delta==null?{text:'—',label:'Draft Fit or source ranking unavailable'}:delta>0?{text:`+${delta} ↑`,label:`Assistant values player ${delta} spots above ${source}`}:delta<0?{text:`${delta} ↓`,label:`Assistant values player ${Math.abs(delta)} spots below ${source}`}:{text:'0 =',label:`Aligned with ${source}`}}
export function rankingsTableMarkup(rows:RankingRow[],mode:RankingMode='FANTASYPROS'):string{const showFp=mode!=='ESPN',showEspn=mode!=='FANTASYPROS';return rows.length?`<div class="rankings-table ${mode.toLowerCase()}" role="table"><div class="rankings-row rankings-header" role="row"><b>PLAYER</b><b>POS</b><b>TEAM</b>${showFp?'<b>FP ECR</b>':''}${showEspn?'<b>ESPN</b>':''}<b>DRAFT FIT</b>${showFp?'<b>DELTA VS FP</b>':''}${showEspn?'<b>DELTA VS ESPN</b>':''}<b>STATUS</b><b>WHY</b></div>${rows.map(row=>{const fp=deltaLabel(row.delta),espn=deltaLabel(row.espnDelta,'ESPN');return`<div class="rankings-row" role="row" data-ranking-player="${escape(row.player.id)}"><b>${escape(row.player.displayName)}</b><span>${row.player.position}</span><span>${escape(row.player.nflTeam??'—')}</span>${showFp?`<span>${row.market.overallRank}</span>`:''}${showEspn?`<span>${row.espn?.overallRank??'—'}</span>`:''}<span>${row.draftFit?.rank??'—'}</span>${showFp?`<strong title="${escape(fp.label)}">${fp.text}</strong>`:''}${showEspn?`<strong title="${escape(espn.label)}">${espn.text}</strong>`:''}<span>${row.available?'AVAILABLE':'DRAFTED'}</span><button data-ranking-why="${escape(row.player.id)}" ${row.draftFit?'':'disabled'}>WHY</button></div>`}).join('')}</div>`:'<p class="empty">No rankings match these filters.</p>'}
