import { describe, expect, it, vi } from 'vitest';
import { makePick, rebuildDraftState, startDraft } from '../domain/engine';
import type { DraftPlayer, DraftUserContext, Position, SeasonSetup } from '../domain/models';
import { playerPool, seedSetup } from '../domain/seeds';
import { emptyPhilosophy } from '../domain/user-context';
import { lockKeepers } from '../domain/setup';
import { buildTeamNeedProfile, detectRecentRun, picksBeforeNextOwnedPick, runRecommendationEngine } from './recommendation-engine';

const context=(setup:SeasonSetup):DraftUserContext=>({philosophy:emptyPhilosophy(setup.league.id,setup.season.id),playerInterests:[],strategicIntents:[],recentConversation:[]});
const userTeam=(setup:SeasonSetup)=>setup.teams.find(t=>t.managerId===setup.managers.find(m=>m.displayName==='Rob Siwicki')!.id)!.id;
const run=(setup=seedSetup('believeland'),players=playerPool(),user=context(setup))=>{if(setup.draft.keeperCount&&setup.keeperLock.status!=='locked')setup=lockKeepers(setup,true);const draft=startDraft(setup,players,setup.draft.keeperCount>0),state=rebuildDraftState(draft);return runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:user})};
const players=(specs:[string,Position,number,number][]):DraftPlayer[]=>specs.map(([id,position,baselineValue,fixtureTier],i)=>({id,canonicalPlayerId:null,displayName:id,normalizedName:id,position,baselineRank:i+1,baselineValue,fixtureTier,byeWeek:6+i}));

describe('deterministic recommendation intelligence',()=>{
  it('is reproducible and completely local',()=>{const fetchSpy=vi.spyOn(globalThis,'fetch');const a=run(),b=run();expect(a.recommendations).toEqual(b.recommendations);expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore()});
  it('never recommends a player at a hard position maximum',()=>{const setup=seedSetup('believeland');setup.positionLimits.find(x=>x.position==='QB')!.maximum=0;expect(run(setup).recommendations.every(r=>playerPool().find(p=>p.id===r.playerId)?.position!=='QB')).toBe(true)});
  it('identifies empty starters and FLEX without treating FLEX as one position',()=>{const setup=seedSetup('believeland'),draft=startDraft(setup,playerPool()),state=rebuildDraftState(draft),profile=buildTeamNeedProfile(setup,state.rosters[userTeam(setup)]);expect(profile.starterNeeds.TE).toBe(1);expect(profile.openFlex).toBe(2);expect(profile.needStrength.RB).toBe(profile.needStrength.WR)});
  it('raises roster fit for an empty starter but permits superior value to win',()=>{const pool=players([['elite-wr','WR',100,1],['te','TE',65,2],['wr2','WR',60,2],['rb','RB',58,2]]),result=run(seedSetup('believeland'),pool);const te=result.recommendations.find(x=>x.playerId==='te')??run(seedSetup('believeland'),pool).recommendations[0];expect(te.breakdown.rosterFit).toBeGreaterThan(0);expect(result.recommendations[0].playerId).toBe('elite-wr')});
  it('increases tier pressure for the last player in a tier',()=>{const pool=players([['last-te','TE',88,1],['next-te','TE',60,2],['wr','WR',80,1],['wr-peer','WR',79,1]]),result=run(seedSetup('believeland'),pool),te=result.recommendations.find(x=>x.playerId==='last-te')!;expect(te.breakdown.tierPressure).toBeGreaterThan(0);expect(te.costOfWaiting).not.toBe('LOW')});
  it('uses league demand so Believeland and keeper-depleted RoboCop differ',()=>{const b=run(seedSetup('believeland')),r=run(seedSetup('robocop'));expect(b.positionPressure).not.toEqual(r.positionPressure);expect(r.teamNeeds.find(x=>x.teamId===userTeam(seedSetup('robocop')))!.positionCounts.QB).toBe(1)});
  it('respects snake timing and traded ownership',()=>{const setup=seedSetup('believeland'),base=run(setup);expect(base.picksUntilNextTurn).toBe(7);const rob=userTeam(setup);setup.ownership=[{seasonId:setup.season.id,round:1,slot:2,originalTeamId:setup.draftSlots[1].originalTeamId,currentTeamId:rob}];expect(run(setup).picksUntilNextTurn).toBe(1)});
  it('has no fake wait window at either snake turn',()=>{
    const setup=seedSetup('believeland'),pool=playerPool();let draft=startDraft(setup,pool);
    for(let i=0;i<11;i++)draft=makePick(draft,rebuildDraftState(draft).available[0].id);
    let state=rebuildDraftState(draft);const team12=setup.draftSlots[11].originalTeamId;
    expect(state.current).toMatchObject({round:1,pickInRound:12,overallPick:12,currentTeamId:team12});expect(picksBeforeNextOwnedPick(state,team12)).toEqual([]);
    draft=makePick(draft,state.available[0].id);state=rebuildDraftState(draft);expect(state.current).toMatchObject({round:2,pickInRound:1,overallPick:13,currentTeamId:team12});expect(picksBeforeNextOwnedPick(state,team12)).toEqual([]);
    for(let i=13;i<24;i++)draft=makePick(draft,rebuildDraftState(draft).available[0].id);
    state=rebuildDraftState(draft);const team1=setup.draftSlots[0].originalTeamId;expect(state.current).toMatchObject({round:2,pickInRound:12,overallPick:24,currentTeamId:team1});expect(picksBeforeNextOwnedPick(state,team1)).toEqual([]);
  });
    it('keeps RoboCop live recommendations at round four',()=>{const setup=lockKeepers(seedSetup('robocop'),true),draft=startDraft(setup,playerPool(),true),state=rebuildDraftState(draft);expect(state.current?.round).toBe(4);expect(run(setup).recommendations).toHaveLength(3)});
  it('detects a recent run without forcing that position',()=>{const setup=seedSetup('believeland'),pool=players(Array.from({length:20},(_,i)=>[i<4?`rb${i}`:`wr${i}`,i<4?'RB':'WR',100-i,i<4?1:2] as [string,Position,number,number]));let draft=startDraft(setup,pool);for(let i=0;i<4;i++)draft=makePick(draft,`rb${i}`);const state=rebuildDraftState(draft);expect(detectRecentRun(state)?.position).toBe('RB');const result=runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:context(setup)});expect(result.recommendations[0].playerId.startsWith('wr')).toBe(true)});
  it('keeps philosophy and interest adjustments bounded and transparent',()=>{const setup=seedSetup('believeland'),pool=players([['qb','QB',90,1],['wr','WR',89,1],['rb','RB',88,1],['te','TE',87,1]]),user=context(setup);user.philosophy.preferences=[{id:'q',category:'QB_TIMING',label:'QB',value:'wait on QB',source:'USER_SELECTED',strength:'SOFT',updatedAt:''}];user.playerInterests=[{id:'f',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'wr',state:'FAVORITE',updatedAt:''},{id:'w',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'rb',state:'WATCH',updatedAt:''}];const result=run(setup,pool,user),qb=result.recommendations.find(x=>x.playerId==='qb'),wr=result.recommendations.find(x=>x.playerId==='wr'),rb=result.recommendations.find(x=>x.playerId==='rb');expect(qb?.breakdown.userPreference).toBeGreaterThanOrEqual(-1.25);expect(wr?.breakdown.playerInterest).toBe(1);expect(rb?.breakdown.playerInterest).toBe(0);expect(wr?.explanationFacts.some(x=>x.text.includes('FAVORITE'))).toBe(true)});
  it('filters hard wait rules and strongly suppresses AVOID',()=>{const setup=seedSetup('believeland'),pool=players([['qb','QB',70,3],['wr','WR',90,1],['rb','RB',89,1],['te','TE',88,1]]),user=context(setup);user.philosophy.preferences=[{id:'q',category:'QB_TIMING',label:'QB',value:'wait on QB',source:'USER_SELECTED',strength:'HARD',updatedAt:''}];user.playerInterests=[{id:'a',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'wr',state:'AVOID',updatedAt:''}];const result=run(setup,pool,user);expect(result.recommendations[0].playerId).not.toBe('qb');expect(result.recommendations[0].playerId).not.toBe('wr')});
  it('returns typed roles, confidence, pulse, WHY facts, and a genuine countercase',()=>{const result=run();expect(result.recommendations.map(x=>x.recommendationType)).toEqual(['BEST_PICK','ALTERNATIVE','BEST_VALUE']);expect(['HIGH','MED','LOW']).toContain(result.recommendations[0].confidence);expect(result.draftPulse.length).toBeGreaterThanOrEqual(2);expect(result.draftPulse.length).toBeLessThanOrEqual(3);expect(result.recommendations[0].explanationFacts.map(x=>x.section)).toContain('UNCERTAINTY');expect(result.recommendations[0].countercase).toContain('alternative')});
});

describe('expanded deterministic recommendation authority',()=>{
 it('keeps the cockpit at three while exposing eight in the same authority order',()=>{const result=run();expect(result.recommendations).toHaveLength(3);expect(result.expandedRecommendations.length).toBeGreaterThan(3);expect(result.expandedRecommendations.length).toBeLessThanOrEqual(8);expect(result.expandedRecommendations.slice(0,3)).toEqual(result.recommendations)});
 it('contains no AI reranking or fabricated percentage confidence',()=>{const result=run();expect(result.expandedRecommendations.every(item=>item.sourceLabel==='DETERMINISTIC INTELLIGENCE')).toBe(true);expect(JSON.stringify(result.expandedRecommendations)).not.toContain('%')});
});
