import { describe, expect, it, vi } from 'vitest';
import { makePick, rebuildDraftState, startDraft } from '../domain/engine';
import type { DraftPlayer, DraftUserContext, Position, SeasonSetup } from '../domain/models';
import { playerPool, seedSetup } from '../domain/seeds';
import { emptyPhilosophy } from '../domain/user-context';
import { robocop2026Philosophy } from '../domain/draft-philosophy';
import { lockKeepers } from '../domain/setup';
import { buildTeamNeedProfile, detectRecentRun, picksBeforeNextOwnedPick, runRecommendationEngine, sourceRankValue } from './recommendation-engine';

const context=(setup:SeasonSetup):DraftUserContext=>({philosophy:emptyPhilosophy(setup.league.id,setup.season.id),playerInterests:[],strategicIntents:[],recentConversation:[]});
const userTeam=(setup:SeasonSetup)=>setup.teams.find(t=>t.managerId===setup.managers.find(m=>m.displayName==='Rob Siwicki')!.id)!.id;
const run=(setup=seedSetup('believeland'),players=playerPool(),user=context(setup))=>{if(setup.draft.keeperCount&&setup.keeperLock.status!=='locked')setup=lockKeepers(setup,true);const draft=startDraft(setup,players,setup.draft.keeperCount>0),state=rebuildDraftState(draft);return runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:user})};
const players=(specs:[string,Position,number,number][]):DraftPlayer[]=>specs.map(([id,position,baselineValue,fixtureTier],i)=>({id,canonicalPlayerId:null,displayName:id,normalizedName:id,position,baselineRank:i+1,baselineValue,fixtureTier,byeWeek:6+i}));

describe('deterministic recommendation intelligence',()=>{
  it('is reproducible and completely local',()=>{const fetchSpy=vi.spyOn(globalThis,'fetch');const a=run(),b=run();expect(a.recommendations).toEqual(b.recommendations);expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore()});
  it('never recommends a player at a hard position maximum',()=>{const setup=seedSetup('believeland');setup.positionLimits.find(x=>x.position==='QB')!.maximum=0;expect(run(setup).recommendations.every(r=>playerPool().find(p=>p.id===r.playerId)?.position!=='QB')).toBe(true)});
  it('identifies empty starters and FLEX without treating FLEX as one position',()=>{const setup=seedSetup('believeland'),draft=startDraft(setup,playerPool()),state=rebuildDraftState(draft),profile=buildTeamNeedProfile(setup,state.rosters[userTeam(setup)]);expect(profile.starterNeeds.TE).toBe(1);expect(profile.openFlex).toBe(2);expect(profile.needStrength.RB).toBe(profile.needStrength.WR)});
  it('raises roster fit for an empty starter but permits superior value to win',()=>{const pool=players([['elite-wr','WR',100,1],['te','TE',65,2],['wr2','WR',60,2],['rb','RB',58,2]]),result=run(seedSetup('believeland'),pool);const te=result.recommendations.find(x=>x.playerId==='te')??run(seedSetup('believeland'),pool).recommendations[0];expect(te.breakdown.rosterFit).toBeGreaterThan(0);expect(result.overallRecommendationAvailable).toBe(false);expect(result.expandedRecommendations.some(item=>item.playerId==='elite-wr')).toBe(true)});
  it('increases tier pressure for the last player in a tier',()=>{const pool=players([['last-te','TE',88,1],['next-te','TE',60,2],['wr','WR',80,1],['wr-peer','WR',79,1]]),result=run(seedSetup('believeland'),pool),te=result.recommendations.find(x=>x.playerId==='last-te')!;expect(te.breakdown.tierPressure).toBeGreaterThan(0);expect(te.costOfWaiting).toBe('LOW');expect(te.costOfWaitingScope).toBe('UNAVAILABLE')});
  it('uses league demand so Believeland and keeper-depleted RoboCop differ',()=>{const b=run(seedSetup('believeland')),r=run(seedSetup('robocop'));expect(b.positionPressure).not.toEqual(r.positionPressure);expect(r.teamNeeds.find(x=>x.teamId===userTeam(seedSetup('robocop')))!.positionCounts.QB).toBe(1)});
  it('respects snake timing and traded ownership',()=>{const setup=seedSetup('believeland');setup.draft.orderStatus='assigned';const base=run(setup);expect(base.picksUntilNextTurn).toBe(7);const rob=userTeam(setup);setup.ownership=[{seasonId:setup.season.id,round:1,slot:2,originalTeamId:setup.draftSlots[1].originalTeamId,currentTeamId:rob}];expect(run(setup).picksUntilNextTurn).toBe(1)});
  it('has no fake wait window at either snake turn',()=>{
    const setup=seedSetup('believeland'),pool=playerPool();let draft=startDraft(setup,pool);
    for(let i=0;i<11;i++)draft=makePick(draft,rebuildDraftState(draft).available[0].id);
    let state=rebuildDraftState(draft);const team12=setup.draftSlots[11].originalTeamId;
    expect(state.current).toMatchObject({round:1,pickInRound:12,overallPick:12,currentTeamId:team12});expect(picksBeforeNextOwnedPick(state,team12)).toEqual([]);
    draft=makePick(draft,state.available[0].id);state=rebuildDraftState(draft);expect(state.current).toMatchObject({round:2,pickInRound:1,overallPick:13,currentTeamId:team12});expect(picksBeforeNextOwnedPick(state,team12)).toHaveLength(22);
    for(let i=13;i<24;i++)draft=makePick(draft,rebuildDraftState(draft).available[0].id);
    state=rebuildDraftState(draft);const team1=setup.draftSlots[0].originalTeamId;expect(state.current).toMatchObject({round:2,pickInRound:12,overallPick:24,currentTeamId:team1});expect(picksBeforeNextOwnedPick(state,team1)).toEqual([]);
  });
    it('keeps RoboCop live recommendations at round four',()=>{const setup=lockKeepers(seedSetup('robocop'),true),draft=startDraft(setup,playerPool(),true),state=rebuildDraftState(draft);expect(state.current?.round).toBe(4);expect(run(setup).recommendations).toHaveLength(3)});
  it('applies Rob’s scoped philosophy to the canonical keeper-built roster',()=>{const setup=lockKeepers(seedSetup('robocop'),true),draft=startDraft(setup,playerPool(),true),state=rebuildDraftState(draft),rob=userTeam(setup),roster=state.rosters[rob],user={...context(setup),philosophy:robocop2026Philosophy()},result=runRecommendationEngine({setup,context:draft,state,userTeamId:rob,userContext:user}),need=result.teamNeeds.find(item=>item.teamId===rob)!;expect(roster.positionCounts).toMatchObject({QB:1,WR:2});expect(roster.positionCounts.RB??0).toBe(0);expect(need.starterNeeds).toMatchObject({QB:0,RB:2,WR:1,TE:1});expect(result.recommendations.every(item=>state.available.some(player=>player.id===item.playerId))).toBe(true);expect(result.recommendations.every(item=>!roster.combined.some(player=>player.id===item.playerId))).toBe(true);const qb=result.expandedRecommendations.find(item=>draft.players.find(player=>player.id===item.playerId)?.position==='QB');expect(qb?.breakdown.userPreference).toBeLessThanOrEqual(0);expect(result.positionPressure.find(item=>item.position==='RB')?.availableCount).toBe(state.available.filter(player=>player.position==='RB').length)});
  it('detects a recent run without forcing that position',()=>{const setup=seedSetup('believeland'),pool=players(Array.from({length:20},(_,i)=>[i<4?`rb${i}`:`wr${i}`,i<4?'RB':'WR',100-i,i<4?1:2] as [string,Position,number,number]));let draft=startDraft(setup,pool);for(let i=0;i<4;i++)draft=makePick(draft,`rb${i}`);const state=rebuildDraftState(draft);expect(detectRecentRun(state)?.position).toBe('RB');const result=runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:context(setup)});expect(result.recommendations[0].playerId.startsWith('wr')).toBe(true)});
  it('keeps philosophy and interest adjustments bounded and transparent',()=>{const setup=seedSetup('believeland'),pool=players([['qb','QB',90,1],['wr','WR',89,1],['rb','RB',88,1],['te','TE',87,1]]),user=context(setup);user.philosophy.preferences=[{id:'q',category:'QB_TIMING',label:'QB',value:'wait on QB',source:'USER_SELECTED',strength:'SOFT',updatedAt:''}];user.playerInterests=[{id:'f',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'wr',state:'FAVORITE',updatedAt:''},{id:'w',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'rb',state:'WATCH',updatedAt:''}];const result=run(setup,pool,user),qb=result.positionAlternatives.find(x=>x.playerId==='qb'),wr=result.positionAlternatives.find(x=>x.playerId==='wr'),rb=result.positionAlternatives.find(x=>x.playerId==='rb');expect(qb?.breakdown.userPreference).toBeGreaterThanOrEqual(-1.25);expect(wr?.breakdown.playerInterest).toBe(1);expect(rb?.breakdown.playerInterest).toBe(0);expect(wr?.explanationFacts.some(x=>x.text.includes('FAVORITE'))).toBe(true)});
  it('filters hard wait rules and strongly suppresses AVOID',()=>{const setup=seedSetup('believeland'),pool=players([['qb','QB',70,3],['wr','WR',90,1],['rb','RB',89,1],['te','TE',88,1]]),user=context(setup);user.philosophy.preferences=[{id:'q',category:'QB_TIMING',label:'QB',value:'wait on QB',source:'USER_SELECTED',strength:'HARD',updatedAt:''}];user.playerInterests=[{id:'a',leagueId:setup.league.id,seasonId:setup.season.id,playerId:'wr',state:'AVOID',updatedAt:''}];const result=run(setup,pool,user);expect(result.recommendations[0].playerId).not.toBe('qb');expect(result.recommendations[0].playerId).not.toBe('wr')});
  it('fails closed without a common overall scale and does not turn TE1 into overall one',()=>{const pool=players([['te','TE',100,1],['rb','RB',90,1],['wr','WR',89,1],['qb','QB',70,2]]);pool.forEach(player=>player.currentPositionRank=1);const result=run(seedSetup('believeland'),pool);expect(result.overallRecommendationAvailable).toBe(false);expect(result.recommendations.every(item=>item.recommendationType!=='BEST_OVERALL')).toBe(true);expect(result.authorityMessage).toMatch(/unavailable/);expect(result.recommendations.every(item=>item.costOfWaitingScope==='UNAVAILABLE')).toBe(true)});
  it('allows verified combined ranks, including an early TE, to drive a definitive pick',()=>{const pool=players([['te','TE',0,1],['rb','RB',0,1],['wr','WR',0,1],['qb','QB',0,2]]);pool.forEach((player,index)=>player.currentBaselineRank=[1,50,51,52][index]);const setup=seedSetup('believeland');setup.draft.orderStatus='assigned';const result=run(setup,pool);expect(result.overallRecommendationAvailable).toBe(true);expect(result.recommendations[0]).toMatchObject({playerId:'te',recommendationType:'BEST_OVERALL',costOfWaitingScope:'COMPARATIVE'})});

  it('uses the three highest final scores without positional diversity',()=>{const pool=players([['rb1','RB',0,1],['rb2','RB',0,1],['rb3','RB',0,1],['wr','WR',0,1],['te','TE',0,1],['qb','QB',0,1]]);pool.forEach((player,index)=>{player.currentBaselineRank=[1,2,3,50,51,52][index];player.currentAdp=[1,2,3,50,51,52][index]});const result=run(seedSetup('believeland'),pool);expect(result.recommendations.map(item=>item.playerId)).toEqual(result.draftFits.slice(0,3).map(item=>item.playerId));expect(result.recommendations.map(item=>item.playerId)).toEqual(['rb1','rb2','rb3']);expect(result.positionAlternatives.find(item=>item.playerId==='wr')?.recommendationType).toBe('BEST_AT_POSITION')});
  it('disables turn-specific claims while Believeland order is unknown and activates them after entry',()=>{const setup=seedSetup('believeland'),unknown=run(setup);expect(setup.draft.orderStatus).toBe('unassigned');expect(unknown.draftSlotKnown).toBe(false);expect(unknown.picksUntilNextTurn).toBeNull();expect(unknown.recommendations.every(item=>item.costOfWaitingScope==='UNAVAILABLE'&&item.expectedReplacementPlayerId===undefined)).toBe(true);expect(unknown.recommendations[0].explanationFacts.some(item=>item.text.includes('My slot unknown'))).toBe(true);setup.draft.orderStatus='assigned';const known=run(setup);expect(known.draftSlotKnown).toBe(true);expect(known.picksUntilNextTurn).toBe(7)});
  it('returns typed roles, confidence, pulse, WHY facts, and a genuine countercase',()=>{const result=run();expect(result.recommendations.map(x=>x.recommendationType)).not.toContain('BEST_PICK');expect(result.overallRecommendationAvailable).toBe(false);expect(['HIGH','MED','LOW']).toContain(result.recommendations[0].confidence);expect(result.draftPulse.length).toBeGreaterThanOrEqual(2);expect(result.draftPulse.length).toBeLessThanOrEqual(3);expect(result.recommendations[0].explanationFacts.map(x=>x.section)).toContain('UNCERTAINTY');expect(result.recommendations[0].countercase).toContain('alternative')});
});

describe('expanded deterministic recommendation authority',()=>{
 it('keeps the cockpit at three while exposing eight in the same authority order',()=>{const result=run();expect(result.recommendations).toHaveLength(3);expect(result.expandedRecommendations.length).toBeGreaterThan(3);expect(result.expandedRecommendations.length).toBeLessThanOrEqual(8);expect(result.expandedRecommendations.slice(0,3)).toEqual(result.recommendations)});
 it('contains no AI reranking or fabricated percentage confidence',()=>{const result=run();expect(result.expandedRecommendations.every(item=>item.sourceLabel==='DETERMINISTIC INTELLIGENCE')).toBe(true);expect(JSON.stringify(result.expandedRecommendations)).not.toContain('%')});
});

describe('Draft Fit rank semantics',()=>{
 it('gives rank 1 a better contribution than rank 100 and invents none when missing',()=>{expect(sourceRankValue(1)).toBeGreaterThan(sourceRankValue(100)!);expect(sourceRankValue()).toBeUndefined()});
 it('uses the sorted available population for ordinals',()=>{const pool=players([['drafted','WR',100,1],['available-1','RB',90,1],['available-2','WR',80,1],['available-3','TE',70,2]]),setup=seedSetup('believeland');let draft=startDraft(setup,pool);draft=makePick(draft,'drafted');const state=rebuildDraftState(draft),result=runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:context(setup)});expect(result.draftFits.map(x=>x.playerId)).not.toContain('drafted');expect(result.draftFits.map(x=>x.rank)).toEqual([1,2,3]);expect(result.draftFits[0].score).toBeGreaterThanOrEqual(result.draftFits[1].score)});
});

describe('truthful bye-week scoring',()=>{
  it('does not penalize an unknown bye and applies only the bounded known overlap penalty',()=>{
    const setup=seedSetup('believeland');
    const pool=players(Array.from({length:20},(_,index)=>[`p${index}`,index%2?'WR':'RB',100-index,1] as [string,Position,number,number]));
    pool.forEach((player,index)=>{player.byeWeek=index===7||index===8?10:index===9?undefined:6+index%8});
    let draft=startDraft(setup,pool);
    for(let index=0;index<8;index++)draft=makePick(draft,`p${index}`);
    const state=rebuildDraftState(draft),user=context(setup);
    user.philosophy.profile!.byeWeekImportance='HIGH';
    const result=runRecommendationEngine({setup,context:draft,state,userTeamId:userTeam(setup),userContext:user});
    const overlap=result.expandedRecommendations.find(item=>item.playerId==='p8');
    const unknown=result.expandedRecommendations.find(item=>item.playerId==='p9');
    expect(overlap?.breakdown.byeWeek).toBeLessThan(0);
    expect(overlap?.breakdown.byeWeek).toBeGreaterThanOrEqual(-.35);
    expect(unknown?.breakdown.byeWeek).toBe(0);
  });
});
